### PR TITLE
Rendering issue

### PR DESCRIPTION
**Pull request by sidis405**
fixed rendering issue on browse bread #715 

This is a previous pull request of mine that apparently had a bug.

screen shot 2017-02-17 at 15 44 55

Minor tweak. It is now fixed.

screen shot 2017-02-17 at 15 48 22

### CODE REVIEW

**Comment by sidis405** [comment]
@marktopper i noticed this today after updating to v0.10.15.
it was the matter regarding the usage of php tags in the blade view as the compiler had issues with other curly braces in the expression.

**Comment by abdgad** [comment]
I haven't tested this. But why are you using `{!! !!}` instead of `{{ }}`?

**Comment by sidis405** [comment]
@abdgad Because blade errors out parsing the following

```
{{ $options->options->{$data->{$row->field}} }}
```

**Comment by abdgad** [comment]
I think it's better to refactor and not use `options->options->{$data->{$row->field}}` because it's hard to read and can cause security issues.

**Comment by sidis405** [comment]
I agree there is quite a bit of refactoring needed in those blade files and even generally.
This pull is meant to fix an actual *breaking issue*, but if you have any ideas how to refactor that expression without starting to dig at the core of the package then i'd be happy to help. :)

**Comment by marktopper** [comment]
Thanks

**Pull request merged**
