### PR TITLE
Revision UI

### PR DESCRIPTION
**Pull request by akazorg**
Some revision to the UI, please read commits.

### CODE REVIEW

**Comment by emptynick** [comment]
In `resources/views/bread/edit-add.blade.php` the Formfields-dropdown does not have the `form-control` class.
Maybe you want to to add this in this PR

**Comment by akazorg** [comment]
Thanks @emptynick, 
I will revise the conflicts and take that into account. The master branch has been updated containing a UI revision so I need to check that.

**Comment by tnylea** [comment]
Hey @akazorg I was having problems resolving some conflicts so instead I just created a new PR and moved over your changed files here: https://github.com/the-control-group/voyager/pull/1613

I'll merge this in as soon as the tests pass on that PR and I'll just close this PR.

Thanks man!

**Comment by akazorg** [comment]
Thanks @tnylea for taking care of it! :)

**Pull request closed without merging**
