### PR TITLE
Remove unnecessary ga-embed.css

### PR DESCRIPTION
**Pull request by davodavodavo3**
Remove unnecessary ga-embed.css from pofile,blade

### CODE REVIEW

**Comment by fletch3555** [comment]
@tnylea, any idea why this CSS file was there? Is it safe to remove?

**Comment by davodavodavo3** [comment]
I dont know, but there is also many javascript files included that are doesnt exists.
Yes you can safe remove that pice of code form there because that file doenst exist.

**Comment by davodavodavo3** [comment]
Tony in resources/views/bread check browse.blade and read.blade.
There are several javascript files that doesnt exist like multilingual,js and dataTables
If need I can remove them in this PR

**Comment by handiwijoyo** [comment]
Hey @davodavodavo3 can you update this PR?

**Comment by marktopper** [comment]
This is save to move, it was deleted in https://github.com/the-control-group/voyager/commit/85ebda1c53c8d32234bbc9a8f4c4087f21af3afc

**Review by marktopper — APPROVED** [review]

**Comment by fletch3555** [comment]
:+1:

**Pull request merged**
