### PR TITLE
Add config option to allow override voyager master view

### PR DESCRIPTION
**Pull request by handiwijoyo**
_config/voyager.php:_

image

### CODE REVIEW

**Comment by akazorg** [comment]
This is a nice one. I think we should also be able to edit all views.

**Comment by fletch3555** [comment]
Does [Overriding views](https://the-control-group.github.io/voyager/docs/#voyager-docs-customization-overriding-views) not already allow this?

**Comment by akazorg** [comment]
@fletch3555 no, this is hard-coded.. all blade files include `@extends('voyager::master')`

**Comment by fletch3555** [comment]
Yes, but Laravel already supports this OOTB: https://laravel.com/docs/5.3/packages#views

**Comment by handiwijoyo** [comment]
@fletch3555 I never notice that! Thanks for pointing that out. I will close this.

**Pull request closed without merging**
