### PR TITLE
Russian translations for Voyager's UI

### PR DESCRIPTION
**Pull request by alexelev**
Added Russian translations for Voyager's UI

### CODE REVIEW

**Comment by alexelev** [comment]
I don't understand why the tests fails :(

**Comment by marco-solare** [comment]
Hi Alex!
First of all it's great that you provide the russian translation, awesome :)

I did the german version and got errors by codeclimate and styleci, too.
I looked into the styleci page of your commit and did not see any suggestions on how to fix them.
strange.

Anyway, the reason might be (in your case, like in mine) maybe this simple thing:
 - trailing whitespaces at the end of the line

That was the problem to styleci in my case.
so I simply fixed it like that:

https://github.com/the-control-group/voyager/commit/648c20026d9a075f72d3741280fcc7b24d083799

maybe try to fix the whitespaces, see if you get less (or no errors) in styleci.

about the codeclimate:
the maintainers of voyager told me that this can be ignored in this case as it is just a language file and it is pretty normal that there will be similar code to other files (because of the translation keys).

so when styleci was green you should be ready to "get pulled" ;)

**Comment by akazorg** [comment]
Hi @alexelev, great job, thank you!

Please follow @marco-solare suggestion.
After fixing it we will merge it. If you need any help, please let us know.

**Comment by akazorg** [comment]
Thank You @alexelev, travis is your friend now!

**Comment by alexelev** [comment]
Thank you for your help, it's great to be a contributor of this project :)

**Comment by akazorg** [comment]
You're welcome :) It's great to see you on board.
Happy coding!

**Pull request merged**
