### PR TITLE
Optionally paginate data type on server-side, avoiding dataTable 

### PR DESCRIPTION
**Pull request by oschettler**
As fix for

* [#444 require pagination for browse data](https://github.com/the-control-group/voyager/issues/444)
* [#422 Problem with BREAD for table with 14k+ rows](https://github.com/the-control-group/voyager/issues/422)
* [#404 Datatable server side in Browse](https://github.com/the-control-group/voyager/issues/404)
* [#156 Table view loading 1 200 000 cities from my database](https://github.com/the-control-group/voyager/issues/156)
* [#81 Add server side pagination to browse](https://github.com/the-control-group/voyager/issues/81)

... I have added a new option _server_side_ to paginate the _browse_ view, using the standard Laravel _paginate()_ method instead of the original approach based on _dataTable_. The default is still to use _dataTable_, but this can now be changed by editing a BREAD and setting the switch:

new-switch

The result is that even big tables now no longer time out in the browser:

pagination

### CODE REVIEW

**Comment by handiwijoyo** [comment]
I think we should use dataTables server side pagination instead of Laravel pagination.

**Comment by karandatwani92** [comment]
Yes, it's very important. Thanks @oschettler 
But Instead of server side. we should ajaxify it using datatables

**Comment by karandatwani92** [comment]
Instead of server side. we should ajaxify it using datatables

**Comment by tnylea** [comment]
@oschettler Very cool! Appreciate the commit. I'm testing it now and I'll be merging it in very shortly.
@handiwijoyo I agree, but for now this will serve as a good solution until someone wants to build the server side pagination with dataTables :)

**Comment by Muhammadinaam** [comment]
This commit is not working correctly.

I added 10,000 users with tinker and then I edited the BREAD and enabled server side option. Then I noticed two problems:

1. Now voyager shows on 15 entries. Next and Previous buttons dont show records after 15 users. I have to manually add (?page=4) at the end of url
bug1

2. When I try to edit BREAD and deactivate server side option and save. BREAD gets saved but server side option is not disabled.

Further, I am not able to show ID of users in browse page. (May be this problem is not related to above commit)

**Pull request merged**
