### PR TITLE
Select query scopes

### PR DESCRIPTION
**Pull request by gabrieljaime**
Hi, As we talked in the #1409 pull, I add the scope options on the selects, in both, dropdown and multiple.
I do not know if it is the best way to do it, but I found it practice. 

This also serves for dynamic scopes.

On the bread you can put
```
{
    "relationship": {
        "key": "id",
        "label": "name",
        "scopes": [
            "currency"
        ]
    }
}
```
or, if you want to use dynamic scope,
```
{
    "relationship": {
        "key": "id",
        "label": "name",
        "scopes": [
            "currency,5"
        ]
    }
}
```
where currency is the name of the scope and 5 is the parameter.

The query may be
`relationshipClass::currency(5)...`

You can also pass more than 1 scope
```
{
    "relationship": {
        "key": "id",
        "label": "name",
        "scopes": [
            "currency,5",
            "active"
        ]
    }
}
```
and again your query:
`relationshipClass::currency(5)->active()...`

I hope it is useful

Regards!.

### CODE REVIEW

**Comment by akazorg** [comment]
I like this. Great job!

**Comment by fletch3555** [comment]
Thanks for this @gabrieljaime! @akazorg, do you have a few minutes to test this? I'm going to be really busy over the next couple weeks.

**Review by akazorg — CHANGES_REQUESTED** [review]
You are repeating around 25 lines of code.
I suggest move this to a single file.
Can you please handle this?

**Comment by tnylea** [comment]
Hey There,

Thanks for this. I can still merge it in, but the way of doing relationships in 1.0 will be new. Checkout this quick video: https://www.youtube.com/watch?v=gnSJ0Z2Fmso&t=53s

Thanks. Talk to you soon.

**Comment by tnylea** [comment]
Actually I was going to close this out since the old way of adding relationships are going to be obsolete soon.

Feel free to open this as another PR for 0.11.4, if you still want to use it and I can look at merging it in there.

Also, checkout the new way that relationships are being created in the dev-master and see if you can implement this in there :)

Thanks a ton! Talk to you soon.

**Pull request closed without merging**
