### PR TITLE
Use views and eager-load menu items

### PR DESCRIPTION
**Pull request by marktopper**
**DO NOT MERGE THIS YET - STILL WORKING ON IT**

- [x] Eager load menu items
- [x] Make view for `admin_menu` type.
- [ ] Make view for `admin` type.
- [ ] Make view for `bootstrap` type.
- [ ] Make view for `default` type.

Currently there is a fallback, so if you enter a `type` which does not have a view, then it will fallback to the original code. However this will be removed once done, since I'm gonna make a view for all of those cases.

It will be backwards compatible, however you might need to update your `voyager` config file to begin using views.

### CODE REVIEW

**Comment by marktopper** [comment]
Fixes #108 

Related to #107 

> Now the Javascript only needs to support unlimited childs, since the view does support it. I might work on this later on.

**Comment by marktopper** [comment]
/ping @tnylea

Would you approve the idea? Would like to know your comments on it before continuing?

**Comment by akazorg** [comment]
Hey @marktopper, you can remove the item "Eager load menu items", it was updated already.
Cheers

**Comment by marktopper** [comment]
@akaZorg, I think you did put in the wrong reference id.

**Comment by akazorg** [comment]
can't find the PR xD it's ok, not important

**Comment by marktopper** [comment]
@akaZorg I will remove it then ;)

**Comment by brandonferens** [comment]
Well, snap. @marktopper this is a much better approach than what I did #196. The menu builder code is pretty confusing and didn't allow for custom views.

We also refactored a few things the same...

**Comment by marktopper** [comment]
@brandonferens. The only problem with this is that my code is breaking changes.
It requires that the user add the new configuration to the configuration in order to work.
I will continue on this and hopefully have something ready to be tested soon, however I am open for feedback and ideas on things to changes, which you might have, since you created the same thing ;)

**Comment by brandonferens** [comment]
Ah, yes. Check out https://laravel.com/docs/5.3/packages#resources and scroll down to `Default Package Configuration`. It allows you to use the default config form within the package, and if the user decides to override any of the values, they can. I've done this a few times. Let me know if you would like some help with it!

**Comment by marktopper** [comment]
Thanks @brandonferens. I will make it work.

Also if you want to help you can just do a pull request to my fork of this (branch `issue-108`).

**Comment by marktopper** [comment]
I'm going to close this and merge #196 instead.
However I will make a new pull request moving the current menu builder code into separate views, just like I started on here for this one.

**Pull request closed without merging**
