### PR TITLE
Make nullable fields insertable

### PR DESCRIPTION
**Pull request by antranapp**
Since the parent_id of Category Model is nullable, we need a way to insert a null value into a field.

screen shot 2017-01-06 at 13 26 33

### CODE REVIEW

**Comment by ghost** [comment]
Why not just make it null if it's blank? :)

**Comment by antranapp** [comment]
See here: http://dev.mysql.com/doc/refman/5.7/en/working-with-null.html
'' IS NULL returns 0, '' IS NOT NULL returns 1, so "empty" and "null" are totally different in the view of mysql.
But anyway, the internet has seemed to discuss a lot about this theme: https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=mysql+null+vs+empty 

Since voyager is a universal admin editor for all kind of projects, I prefer to give user a chance to enter "NULL" and "empty" separately. You will never know what kind of requirements could be.

I'm totally ok if anyone can implement another solution and make inserting nullable possible. I'm currently using this solution for my needs.

**Comment by marktopper** [comment]
@peacemoon: Instead of hardcoding it, how would you feel about making it into an option, like this:

```
{
    "null": "__null__"
}
```

Meaning that `__null__` will become `null`.

In this case, a empty string can become null by setting:

```
{
    "null": ""
}
```

**Comment by antranapp** [comment]
@marktopper this is a great idea. It will be then flexible enough for everyone. I'll adapt my pull request according to your suggestion.

**Comment by marktopper** [comment]
Creating work, merging in now. 👍

**Comment by hazem1taha** [comment]
@marktopper @peacemoon 
I get this error when using this json option for the parent_id field and making it nullable:

`{
    "relationship": {
        "key": "id",
        "label": "name"
    },
    "default": "null",
    "options": {
        "null": "Main category"
    }
}`

the error:

`QueryException in Connection.php line 770:
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'null' for column 'parent_id' at row 1 (SQL: update `categories` set `parent_id` = null, `updated_at` = 2017-01-08 11:06:11 where `id` = 4)`

**Comment by marktopper** [comment]
I believe it tries to insert `"null"` as a string and not a `null` value.

In order to make it parse a string into a `null` value, define the following:

```
{
    "null": "null"
}
```

Then the string `"null"` will become a `null` value.

**Comment by hazem1taha** [comment]
Here is what I'm doing:
adsl

Here is the error I get:

`QueryException in Connection.php line 770:
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'null' for column 'parent_id' at row 1 (SQL: update `categories` set `parent_id` = null, `updated_at` = 2017-01-08 20:50:51 where `id` = 3)`

Am I missing something ? anyway I'll wait for the new version you said it will be available today.

**Comment by antranapp** [comment]
Use this:
{ "relationship": { "key": "id", "label": "name" }, "default": "null", "null": "null", "options": { "null": "Main category" } }

**Pull request merged**
