### PR TITLE
Added Arabic language files

### PR DESCRIPTION
**Pull request by MujtabaFR**
Complete translation of the language files to **Arabic** ..
Thanks to [the old translation](https://github.com/the-control-group/voyager/pull/1360/files) done by @mbdwey which helped me alot

### CODE REVIEW

**Comment by akazorg** [comment]
Thanks for this. 
I'm just not sure how to handle the default Laravel translations. @marktopper @fletch3555 any idea?
I'll merge this later when we find a solution for that.

**Comment by marktopper** [comment]
I will go through this today and ensure that the translations work.

**Comment by marktopper** [comment]
@MujtabaFR: Why have you added the `auth.php`, `pagination.php`, `passwords.php` and `validation.php` files?

**Comment by MujtabaFR** [comment]
@marktopper: I thought that the translation of these files may be helpful, but I'm not sure if you want it or not.
I've tested the translated `auth.php`, `passwords.php` files at the **login page** and they were working fine

**Comment by akazorg** [comment]
If we ship those files (auth, pagination, passwords, ...), then we should ship other languages as well.

**Comment by MujtabaFR** [comment]
Actually the files `auth.php`, `pagination.php` and `passwords.php` are useful and pretty easy to translate.
Only the file `validation.php` is large and not that useful to be translated.

Please do what's better for you, either **skip** these files, or **ship** them and wait the other languages to follow later

**Comment by marktopper** [comment]
Please **skip** them, instead people can use this package to get the default Laravel language strings in their language.
https://github.com/caouecs/Laravel-lang

**Comment by MujtabaFR** [comment]
Ok @marktopper 

Actually I didn't know that they were default Laravel files, and already translated .
Sorry for this misunderstanding and hope you mention the [Laravel lang link](https://github.com/caouecs/Laravel-lang) in the documentation later so it will be clear for people how to properly translate there website

Now would you like me to delete the files `auth.php`, `pagination.php`, `passwords.php` and `validation.php` from the pull request ?

**Comment by marktopper** [comment]
It is okay, I'm just glad you translated the `voyager.php` file.
Yes, please remove the other files from the pull request.

And sure, I will make sure to mention that link in the documentation, working on the translation/i18n/multi-lingual documentation as we speak.

**Comment by MujtabaFR** [comment]
Deleted them 👍

**Comment by marktopper** [comment]
Thanks 👍

**Comment by mbdwey** [comment]
@marktopper Thanks

**Pull request merged**
