### PR TITLE
Fix small type at login failure

### PR DESCRIPTION
**Pull request by denbatte**

### CODE REVIEW

**Comment by marktopper** [comment]
Please also update the test for this: https://github.com/the-control-group/voyager/blob/master/tests/LoginTest.php#L30

**Review by marktopper — CHANGES_REQUESTED** [review]
Test must be changed according to this

**Comment by ctf0** [comment]
all error msgs should be saved in a lang file instead of hardcoding it

**Comment by Frondor** [comment]
Yeah, @ctf0 is right. I wrote `trans('auth.failed'')` because it should support the current `app.locale`.
That error message shouldn't be hardcoded anymore.

If I remember well, this is fine on v0.11

**Comment by fletch3555** [comment]
@denbatte, @Frondor,

Should this be closed?  No activity in 2 months, and I'm not quite sure what the status is

**Comment by Frondor** [comment]
@fletch3555 indeed :+1:

**Pull request closed without merging**
