### PR TITLE
Added Backend-Translations

### PR DESCRIPTION
**Pull request by emptynick**

### CODE REVIEW

**Comment by emptynick** [comment]
Yes, I saw it after uploading this one...stupid me

**Comment by marktopper** [comment]
We have decided to go along with the original translations instead of using JSON.
I will fix the tests and merge conflicts and then merge this in.

Thanks @emptynick

**Comment by akazorg** [comment]
Hello @emptynick, after all we will use your work! Well done :)

@marktopper should we group translations per type? ([see translations](https://github.com/the-control-group/voyager/blob/e0cf3e24354456255dd724cc88af930006fee81f/publishable/lang/voyager.php))
So instead of:
```
return [
    ........
    //Generic
    'generic_email'                     => 'E-mail',
    'generic_password'                  => 'Password',
    'generic_login'                     => 'Login',
    'generic_dashboard'                 => 'Dashboard',
    'generic_profile'                   => 'Profile',
    'generic_settings'                  => 'Settings',
    'generic_options'                   => 'Options',
    ...
```

Have something like:
```
return [
    ........
    'generic' => [
        'email'           => 'E-mail',
        'password'        => 'Password',
        'login'           => 'Login',
        'dashboard'       => 'Dashboard',
        'profile'         => 'Profile',
        'settings'        => 'Settings',
        'options'         => 'Options',
        ...
    ],
```

**Comment by AdrianKuriata** [comment]
Wow, big step, nice guys :)

**Comment by marktopper** [comment]
@akazorg, let's group it.

**Comment by AdrianKuriata** [comment]
Did you will create translations for languages or you let translate voyager for developer with export from vendor?

**Comment by marktopper** [comment]
The plan is to have translations located in the vendor file and loaded, however will make it possible to overwrite.

**Comment by marktopper** [comment]
Merging this into `i18n` and then I will fix the tests and make the grouping.

**Comment by pboethig** [comment]
Nice ! .Do you have some docs how to translate the app. I have setup DE as config and translated loginscreen, but tehere are no changes if i open the screen. How to use the i18n feature.

**Comment by emptynick** [comment]
I will provide DE language ASAP

**Comment by pboethig** [comment]
Sounds great. How can I activate a languagefile? Is there a custom implementatio  or Laravel standard? I cant see any "messages.php" under  resources/lang. Some docs would be great too!

**Comment by AdrianKuriata** [comment]
Probably this is in i18n, not in official package, mark said he must fix it and maybe at couple days we will se update with it, you must be patient.

**Comment by pboethig** [comment]
thx

2017-06-17 18:43 GMT+02:00 AdrianKuriata <notifications@github.com>:

**Comment by pboethig** [comment]
It is very important, that we can translate the views and the overrides too. Please keep that in mind, Since 5.4 there are good translationing possibilities. I suggest to use the laravel methods for that.
Kind regards

Peter

**Comment by pboethig** [comment]
Yes. thats my problem atm, understand. How is it possible to translate the voyager views and its customizations?  If you dont use laravel standard, its very difficult.
I suggest to read all messages.php of standard laravel from lang/de/messages.php and merge the translations with voyagher translations. I would look in the standard laravel overrides for package translations. Perhaps its possible to override the __() or @lang() to get it right.

I think, It musst be possible to keep laravel comptibility. Otherwise it could come to terrible problems.

Hope you find a good solution. I am waiting hopefully. This is such a promising project !

**Pull request merged**
