### PR TITLE
Add user-role-permission-builder #240

### PR DESCRIPTION
**Pull request by handiwijoyo**
See #240 for details.

### CODE REVIEW

**Comment by fletch3555** [comment]
Tested briefly and looks great!  I'll let @marktopper and/or @tnylea take a look as well before this gets merged in.

My only concern is how big the permissions list may get.  Is there a way we could refactor the UI for that so it's a little more compact? (Can be a new issue, doesn't have to be built into this PR)

**Comment by handiwijoyo** [comment]
@fletch3555 Thanks. This PR will be only basic implementation of permissions. Once it merged, we can add more patch/feature.

For example, I want to move the permission checking to somewhere else https://github.com/the-control-group/voyager/blob/4c89f10397227c7a46af4a8d394a31222d7ed3a9/src/Http/Controllers/VoyagerBreadController.php#L421

**Comment by akazorg** [comment]
Hello, nice job here.
Personally I would use roles only, like we have now, but it's just my opinion.
I think users should be able to have multiple Roles, and not to have a single role associated with.

**Comment by marktopper** [comment]
Can you fix the conflicts? Then I will merge in.

**Comment by handiwijoyo** [comment]
@marktopper resolved!

**Pull request merged**
