### PR TITLE
added voyagercheckmaintenancemode middleware

### PR DESCRIPTION
**Pull request by allenjd3**
This is a potential solution to #1947

This would require some method of stubbing the Kernel when you install voyager. The kernel would need to register this checkmaintenancemode middleware rather than the default- something like-

    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \App\Http\Middleware\TrustProxies::class,
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \TCG\Voyager\Http\Middleware\VoyagerCheckForMaintenanceMode::class,
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],

        'api' => [
            'throttle:60,1',
            'bindings',
        ],
    ];

notice how I removed the default checkForMaintenanceMode middleware from the middleware array and added the voyager one to the web group. (It can't be in the middleware group because I need access to the request object). 

Anyway, Is there a way to stub out the Kernel or would that have other potential side affects?

### CODE REVIEW

**Comment by allenjd3** [comment]
Looks like I didn't take out the Route Facade that I ended up not using. I can resubmit if necessary

**Comment by fletch3555** [comment]
I'm not sure how I feel about this fix, though it would very likely work.  At the very least, you should probably be extending the laravel middleware instead of creating one outright.

**Comment by allenjd3** [comment]
There are a couple ways it could be used- it could be an optional feature that you opt into by changing your own kernel, it could be a stub that you optionally install to your own middleware folder so you have access to the whitelist-

I could maybe change it to extend laravel's checkformaintenancemode middleware but I have a feeling I would be overriding everything anyway.

**Comment by fletch3555** [comment]
If you extend the built in one, you won't need to do half of what you have.  You could do something along the lines of:

```
if (/* current route is in voyager */) {
    return $next($request);
}
else {
    return parent::handle($request, $next);
}
```

**Comment by allenjd3** [comment]
Ah I see,

The only potential downside I see on that would be that you would be checking every request against the whitelist rather than just the ones that are down for maintenance. I'm not positive but it seems like that would be slower. I'll mess around with it some tonight to try and extend the laravel one.

**Comment by allenjd3** [comment]
I extended the checkformaintenancemode middleware and cleaned some stuff up. I made it a middleware that runs after the request so you can just replace the default middleware with the one thats extended

    protected $middleware = [
        \TCG\Voyager\Http\Middleware\VoyagerCheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
    ];

I left the reference to app in there so it can run the check against the whitelist only on the requests that are in maintenance mode.

**Comment by fletch3555** [comment]
You can't run it after the request.  The whole point of maintenance mode is to prevent requests to the application that will likely break during system maintenance (i.e. you have to take down a dependency and it'll just throw errors if the requests are allowed to proceed)

**Comment by allenjd3** [comment]
You need access to the request object for it to work- might have to fix it a different way then

**Comment by fletch3555** [comment]
You already have access to the $request object....

**Comment by allenjd3** [comment]
It's null until you pass out of the default middleware group which is why I originally put it in the web group. I don't think laravel registers the request until after you get past that point

**Comment by allenjd3** [comment]
https://stackoverflow.com/a/31868954

**Comment by fletch3555** [comment]
I'm going to decline this for now.  I don't believe it needs to be in Voyager's Core.  Feel free to make it into a Hook.  I'm sure someone will find it useful.

Thank you.

**Pull request closed without merging**
