### PR TITLE
Fixed new fields don't appear in BREAD edit

### PR DESCRIPTION
**Pull request by DODMax**
There is a bug in #1165
Fields added in DB edit but not yet saved in data_rows table do not appear.
See https://github.com/the-control-group/voyager/pull/1165#discussion_r114070870

### CODE REVIEW

**Comment by akazorg** [comment]
Can you fix the StyleCI please?
Great job.
Thanks

**Comment by fletch3555** [comment]
Don't worry about StyleCI, it'll fix itself

**Comment by akazorg** [comment]
I dint know about that auto-fix. Nice

**Comment by akazorg** [comment]
Just tested. Thanks @DODMax, nice job!

**Comment by DODMax** [comment]
👍 
Thank you too, happy to participate

**Comment by ghost** [comment]
i have the same problem in laravel 5.5.1 and voyager dev-master

**Pull request merged**
