### PR TITLE
Feature/multilangual

### PR DESCRIPTION
**Pull request by akazorg**
This is a working version for the multilingual system, supporting BREAD and Menu translations.

Theres a seeder included, for install remember to use "--with-dummy".

Your feedback is important and more then welcome!
Happy coding :)

### CODE REVIEW

**Comment by turtuga** [comment]
I think it's tracke old commits :(

**Comment by fletch3555** [comment]
@akazorg, can you please pull/merge tcg/master into your branch? It's currently showing ~250 changed files and many of them weren't your changes.

**Comment by abdgad** [comment]
@fletch3555 the problem is with `tcg:feature/multilangual` branch, it's behind master.

**Comment by akazorg** [comment]
I followed that procedure @fletch3555. How can we sort that?

**Comment by marktopper** [comment]
Merging this into `tcg/feature/multilangual` and then I will be fixes the conflicts at that branch.

**Pull request merged**
