### PR TITLE
Migrations independent of users table

### PR DESCRIPTION
**Pull request by jmarcher**
In my case my not only the User model is different, also the database name is different.

That's why I made this changes in order use the table name based on the model.

That means that you if you publish you vendors and then edit the namespace the migrations will take this user to resolve the user's table name

### CODE REVIEW

**Comment by fletch3555** [comment]
I'm not sure how I feel about this.  To me, the migrations get published, so you (as the developer) are free to update them as you see fit.

**Comment by jmarcher** [comment]
The problem is that if you only run voyager:install and you don't have a users table this command fails.

**Comment by abdgad** [comment]
There are some problems with the current installation process. I will make a PR later and we'll discuss it further = )

**Comment by abdgad** [comment]
@marktopper @jmarcher @fletch3555  what about including a create_users_table migration with Voyager, and add a config setting to specify users table? And all user migrations will use the table from the config..?

**Comment by marktopper** [comment]
@abdgad: How would that work for existing Laravel applications that already have a `users` table?

**Comment by marktopper** [comment]
This does not seems ideal.

Maybe we could do something like [this](https://github.com/jrean/laravel-user-verification/blob/master/src/resources/migrations/2016_09_13_070520_add_verification_to_user_table.php).

But use the `voyager.user.namespace` as model if defined. That will allow users to change that in order to change the migrations?

Open for other ideas, however this does not seem ideal.

**Pull request closed without merging**
