### PR TITLE
Cleaning the src folder

### PR DESCRIPTION
**Pull request by arcanedev-maroc**
**NOTICE :** Don't merge it yet, i'm still working on it 😉 

@tnylea can you review the changes ?

**TODO:**
* [x] Moving routes & views outside the `src` folder.
* [x] Moving Controllers & Middleware into `Http` folder.
* [x] Refactoring/Cleaning Controllers.
* [x] Updating the `VoyagerServiceProvider` :
    * Refactoring/Updating the publishable files to `registerPublishableResources()` method.
    * Extract routes from `boot()` method to `registerRoutes()` method.
    * Extract commands.
    * Call the `registerPublishableResources()` & `registerCommands()` methods only if the app is running in console.
* [x] Removing the unused namespaces.
* [x] Using the Class name resolution via `::class` instead of string.
* [x] Using the full class name for Facades instead of aliases.
* [x] Using directly the `Illuminate\Support\Arr` or `Illuminate\Support\Str` class instead of the helpers (We leave the helpers just for views or something similar).

### CODE REVIEW

**Comment by tnylea** [comment]
@arcanedev-maroc ok, keep me posted and I can review the changes :)

Thanks.

**Comment by arcanedev-maroc** [comment]
Hi @tnylea, you can check the changes now.

I don't know if i broke some logic because refactoring without test units is a bad thing to do.

But at least we have cleaner code now 😉 

**Next thing to do in future:** Testing with [orchestral/testbench](https://github.com/orchestral/testbench).

**Comment by marktopper** [comment]
I can take a look at it.

**Comment by arcanedev-maroc** [comment]
Hi @marktopper, go ahead 👍 

I've just rebased the PR and i hope i didn't mess something 😜

**Comment by arcanedev-maroc** [comment]
I've just check the file changes and i still have work to do.

Especially restoring the old changes made by others contributors.

**Comment by marktopper** [comment]
Just looked through the changes, and from what my eye could catch, it all looked fine.

However once your done I will do a proper test of this, just ping me.

However great work 👍

**Comment by arcanedev-maroc** [comment]
Hi @marktopper, you can start the testing the changes.

Don't forget to review the changes (+comments) if i forget something, i've a hard time to solve the conflicts 😭

Best regards

**Comment by marktopper** [comment]
I will look into it now before any other conflicts comes by.

**Comment by marktopper** [comment]
Finally done testing this!
Good job 👍

**Pull request merged**
