### PR TITLE
Allow null values change from request

### PR DESCRIPTION
**Pull request by TimurGit**

### CODE REVIEW

**Comment by marktopper** [comment]
Please explain what you are trying do in this pull request.
Thanks 👍

**Comment by TimurGit** [comment]
@marktopper The problem was in saving the empty field values display_name in the role entities.
I open role:
image
Change display_name to empty
image
After Saving
image
I have enabled default middleware \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class
If it's disabled then there is no error

**Comment by marktopper** [comment]
Please separate the changes into multiple pull requests.

**Comment by fletch3555** [comment]
@TimurGit. please update your branch from `voyager/master`.  You can do this by adding an `upstream` git remote (`git remote add upstream [voyager repo url]`).  Once it's been added, you can do `git fetch upstream` and `git merge upstream/master`

After you do this, I suspect we'll be able to see just your changes for this PR, and can reopen it for review.  Please do NOT open a new PR for this change, we'll use this one once it's cleaned up.

**Comment by TimurGit** [comment]
@fletch3555 , Thank you. I added remote repository in my branch.
Pull request is not actual. Bug was fixed in other commits.

**Pull request closed without merging**
