### PR TITLE
Support of multiple file upload. As requested in #595

### PR DESCRIPTION
**Pull request by lampdev**
As requested in #595:

- Allowing multiple file upload by default. Using the original 'file' type

- saving original filename in json in the DB for better outlook of the download link

- removing files once the entity is deleted

### CODE REVIEW

**Comment by fletch3555** [comment]
@lampdev, Just an FYI for future pull requests.  You can safely ignore StyleCI and CodeClimate failures unless we explicitly request that you change them.

**Comment by tnylea** [comment]
@lampdev has this been completed yet. I'm trying to test out a multiple file upload, but it's only letting me upload one image. When I try and view the data in the database for a file upload it just gives me an empty array:

```
[]
```

Let me know if there's anything I can do to help with testing this further before confirming the Merge Request :)

Thanks.

**Comment by tnylea** [comment]
@lampdev actually sorry, I didn't switch to your `multiple-files` branch. But after doing so, I went to test out a multiple file upload. I switched the pages `image` to be `mutiple-images` and after doing so I tried creating a new page with 2 images and got the following message:



Any thoughts? Let me know 👍 

Thanks.

**Comment by lampdev** [comment]
@tnylea Hi and thanks for testing this! I haven't done anything with `multiple_images` field type, only modified the `file` type

**Comment by tnylea** [comment]
@lampdev aha, ok. Thanks for clarifying.

I'll be testing again tomorrow. BTW, just merged in the `coords` functionality and that will be available when we release 1.0 👍

**Pull request merged**
