### PR TITLE
Updated default data type for timestamp column

### PR DESCRIPTION
**Pull request by sanampatel**
Updated default data type for timestamp column from timestamp to datetime, which resolve the error!

### CODE REVIEW

**Comment by fletch3555** [comment]
> which resolve the error!

What error? Is there an open issue? We need more detail than this.

**Comment by sanampatel** [comment]
Just changed to datatype to datetime from timestamp. Cause timestamp data type is not available, which gives error while adding timestamp in database creating form!

image

**Comment by fletch3555** [comment]
You need to either fully document the issue you're reporting (and supposedly fixing), or link to an issue that does.  We can't blindly accept changes without knowing why they're made.

**Comment by fletch3555** [comment]
Closing.  We can reopen this once my previous question is answered.

**Pull request closed without merging**
