### PR TITLE
Add ability to select user roles on users data type

### PR DESCRIPTION
**Pull request by handiwijoyo**
Add ability to select user roles when create or edit user.

image

### CODE REVIEW

**Comment by fletch3555** [comment]
This is a good start, but seems too specific.  I'd rather see a solution where you can add fields like this to handle relations elsewhere.  So if I manually edit a model (generated or otherwise), and add a many-to-many or one-to-many relation to it, I'd like that field to be editable like you have here.

**Comment by fishmad** [comment]
Why did this get deleted its what we need?

**Comment by tomicakorac** [comment]
@fishmad because the solution was too specific. It would be more practical to have a universal solution for any kind of model relations, not just the user-role relation.

By the way, I was wondering, has anyone tried using Voyager along with other packages for user role management,such as Zizaco's entrust, or some other? How would that work out, if at all?

**Comment by joshuatf** [comment]
Added a many to many relation option that works for this on issue #188 

@tomicakorac Middleware seems to be hardcoded in, but I would also like to see the ability to use Entrust or other packages here.  Frozennode admin package has a permission option in their configuration that works perfectly for this and allows you to use any method or package you'd like.  

That works for general access, but menu item visibility and permission for specific CRUD actions on models also needs to be addressed.  Willing to take the ball on this, but I don't think the JSON options is a good place to stick this.

**Pull request closed without merging**
