### PR TITLE
Update voyager.php

### PR DESCRIPTION
**Pull request by gwleuverink**
translated a forgotten word

### CODE REVIEW

**Comment by fletch3555** [comment]
Please open a new PR for this change, but on the `master` branch.  `develop` is for future releases containing backwards incompatible changes

**Comment by gwleuverink** [comment]
@fletch3555 Of course. The original Dutch translation was accepted in the develop branch tough and is not merged to master yet. Shall I PR the whole file?

**Comment by fletch3555** [comment]
Can you provide a link to the one that was accepted to develop? It's likely a mistake

**Comment by gwleuverink** [comment]
@fletch3555 https://github.com/the-control-group/voyager/pull/2082

**Comment by fletch3555** [comment]
Yeah, that one was a mistake.  Apologies for the confusion.  I'm going to reopen this and accept it into develop anyway.  The Dutch translation will have to go out with v1.1

**Comment by gwleuverink** [comment]
Thanks!

**Pull request merged**
