### PR TITLE
Datatables more beautifull

### PR DESCRIPTION
**Pull request by turtuga**
Merge only if you like :)

before

after

### CODE REVIEW

**Comment by fletch3555** [comment]
Assigning @thedevdojo to review style changes.

**Comment by tnylea** [comment]
@turtuga I like it but I feel like it's a little too dark, try this color: #F6F8FA, this is the same color as the panels used here on github, it is very subtle and looks nice :)

Thanks.

**Comment by turtuga** [comment]
@tnylea done I like it too :) thanks

**Comment by tnylea** [comment]
Awesome. Thanks. Merging in :)

**Pull request merged**
