### PR TITLE
Fix for saving field like a null

### PR DESCRIPTION
**Pull request by AdrianKuriata**
I fixed possibility to saving field like a null. I thougth rules validation like "`sometimes|nullable`" will be enough but wasn't. When we tried to save empty field, it was not active into $date variable so we need remove this part of code for let us saving field like a empty(null) value. I tested it and i don't see any issues, but if someone could test it again, i will be appreciated.

@akazorg I tested issue with rules and it was not worked so i did a PR for fix it.
#1331

### CODE REVIEW

**Comment by akazorg** [comment]
Great job, I'll test that out ASAP!!

**Comment by akazorg** [comment]
Merged

**Comment by MujtabaFR** [comment]
Hello,
When performing the suggested change (deleting the few lines).. I found an issue with the **image field**
If I'm editing a post which already has an image uploaded for it. When saving it (without changing the image field) .. The image becomes null and will be removed from the post and the database

Guess it will be the same issue with the **File field**, but I didn't test it yet

**Comment by akazorg** [comment]
The feature for delete an existing image/file is currently missing. We need to place a delete button and handle that procedure.

**Pull request merged**
