### PR TITLE
Fix #1737 (and others)

### LINKED ISSUE #1737: Menu sort order not working in custom blade
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version: 7.0.8
- Database Driver & Version:

### Description:
I created a menu in Voyager admin and added three items. I sorted them in another order. 

When I create a blade to build my own custom markup, the sort order if the items is wrong. I can't see a logical pattern to how it is sorted. 

The blade only contains the default code from: https://voyager.readme.io/docs/menus
```
<ul>
    @foreach($items as $menu_item)
        <li><a href="{{ $menu_item->url }}">{{ $menu_item->title }}</a></li>
    @endforeach
</ul>
```

Looking at the content of $items `<?=$items?>`
 the "order" key is correctly set, but the list is not sorted by it.

### Steps To Reproduce:

see above

### PR DESCRIPTION
**Pull request by fletch3555**
Moving MenuItem sort functionality from view to controller

### CODE REVIEW

**Comment by tnylea** [comment]
Doesn't seem to be working in the builder.

Something got messed up in the order. Take a look at this screenshot:

screen shot 2017-09-18 at 1 10 50 pm

Now, when I go to the menu builder for the admin, this is what I'm seeing:

screen shot 2017-09-18 at 1 11 06 pm

Which does not match up with the actual menu.

Let me know when this has been fixed and I can merge it in 👍

**Comment by davodavodavo3** [comment]
Еverything works for me with @fletch3555 commit

**Comment by fletch3555** [comment]
@davodavodavo3, can you just confirm that the normal Admin menu works correctly for you? @tnylea's screenshots seem to indicate otherwise.

**Comment by davodavodavo3** [comment]
How do you want me to confirm?))))
I made your changes with my package and the menu works fine, and sorts(order) normally as I specify.

**Comment by davodavodavo3** [comment]
And what, you commit non-working code?
You did not test yourself?

**Comment by tnylea** [comment]
@davodavodavo3 The admin menu works fine, but when you go into the builder it does not seem to reflect the same.

I'll take a look at this as well to see what's going on.

**Comment by fletch3555** [comment]
I did test that it fixed the problem, but I didn't have a chance to look at the admin menu, which is what @tnylea tested.  I had to run and was unable to confirm what he found.  Now I'm mobile, so I don't have an environment to test in.

You can test by simply installing the branch (`composer require tcg/voyager dev-bugfix/fix-1737`), then logging into Voyager.  Try re-ordering it in the menu builder and confirm the order in the Voyager admin menu matches the order in the menu builder.

**Comment by tnylea** [comment]
Hey Guys,

I just tested and it worked fine for me.

MY BAD for holding this up. I had so much on my plate today. Merging it in 👍

**Comment by davodavodavo3** [comment]
Ohh @tnylea i remove my Voyager Admiinnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn for testing your issue))))))))))))))))))))))))))))))))))))))))))))

**Pull request merged**
