### PR TITLE
Order Bread Items

### PR DESCRIPTION
**Pull request by emptynick**
Allows you to order your BREAD-Items with drag & drop .
To use it you have to do the following:

1. Run migrations. It will not work if you dont ( but it will be invisible and not crash )
2. Set the proper options (Order column and Order ident column) in the bread options.
3. Now in Bread-browse you will find a button "Order" at the top.
4. Click on it and you will be able to rearrange your items.

Maybe the naming could be different - please let me know, as I'm not a native english speaker ;)

### CODE REVIEW

**Comment by fletch3555** [comment]
Are all of the lang file changes necessary for this PR? If so, please resolve the conflicts by pulling master into your branch.

**Comment by emptynick** [comment]
Yes they are kind of necessary. Of course I could remove all those tooltip-messages, but I think no one would get the thing then.
Will start to resolve it now.

**Comment by fletch3555** [comment]
I'm inclined to say this needs to get punted to `v1.1`, primarily due to the needed migration

**Comment by emptynick** [comment]
No worries.
We can look at this again when the time has come.
One thing as a reminder for myself:
When the order_column is set the browse page could automatically order it by this field.

**Comment by fletch3555** [comment]
I changed the base branch to `develop` so we can work on getting it in for v1.1, but there's a number of merge conflicts (`master` needs to be pulled into `develop`).  Don't worry about the excess noise in here.  It'll be resolved once we get develop updated.

**Comment by emptynick** [comment]
Closing in favor of #2827

**Pull request closed without merging**
