### PR TITLE
Add alert for missing storage symlink

### PR DESCRIPTION
**Pull request by marktopper**
## Progress:
- [x] Make alert system
- [x] Make missing storage symlink alert
- [x] Make missing storage symlink alert action (that creates the storage symlink)

## Screenshots of "missing storage symlink" alert
skaermbillede 2017-01-07 kl 12 08 42
skaermbillede 2017-01-07 kl 12 08 52

## How to add new alerts?
```
Voyager::addAlert(
    new Alert('codename', 'type')
        ->title('A awesome title')
        ->text('Some text')
        ->text('Some more text')
        ->button('Click me', '#link', 'style');
);
```

### CODE REVIEW

**Comment by handiwijoyo** [comment]
I got error when click Fix It button

**Comment by handiwijoyo** [comment]
@marktopper I got error when click `Fix It`

image

But, the symlink was created successful inside my public

image

Then, I refresh the dashboard and the error gone.

image

**Comment by marktopper** [comment]
Thanks @handiwijoyo. Will update the check.

**Comment by handiwijoyo** [comment]
@mark I added checking if the storage folder was created.

image

**Comment by marktopper** [comment]
Nice @handiwijoyo 👍

**Pull request merged**
