### PR TITLE
Added Romanian language

### PR DESCRIPTION
**Pull request by NicolaeCasir**
Added romanian language... and missing keys(in en and ro) for relationships))

### CODE REVIEW

**Comment by fletch3555** [comment]
You have a conflict, most likely due to the extra commit in your master branch (you should be using other branches by the way).  Please pull master into your branch and see if that resolves the issue.

**Comment by NicolaeCasir** [comment]
@fletch3555 , now i'm adding missing keys... after will pull and try again.

**Comment by NicolaeCasir** [comment]
Done!! Added romanian and some keys relationships was unable to translate, plain text, i added keys)) Was a pleasure for me))

**Comment by fletch3555** [comment]
You still have a number a number of extraneous changes that are unrelated to this PR.

**Comment by NicolaeCasir** [comment]
What changes? Just added romanian + Added keys for relationships...because there was only plain text))

**Comment by fletch3555** [comment]
You have a commit preceding the language changes: https://github.com/the-control-group/voyager/pull/2092/commits/d360977c6ada346e79c0d2c6783a2d81a110b6c9

Also, your most recent commit was a merge that also made other changes.  Doing that is strongly discouraged as it blurs the changeset so we can't easily tell what you've changed.  I'm going to re-do the changes in a new branch just to simplify the process.

**Comment by fletch3555** [comment]
@NicolaeCasir, please review #2114 to verify all of the appropriate changes are there.

**Pull request closed without merging**
