### PR TITLE
Settings grouping

### PR DESCRIPTION
**Pull request by emptynick**
Lets you group Settings with a custom text/name.

groups

### CODE REVIEW

**Comment by tnylea** [comment]
@emptynick dude! This kicks ass 👍 

I've actually wanted this for quite awhile. I'm testing it out right now. I'm wondering why Travis CI is failing. Looking into it further.

**Comment by tnylea** [comment]
@emptynick, I love this addition. I just pushed a change so that way the Travis CI tests will pass.

I also added 4 different permissions, which are

 - read_settings
 - edit_settings
 - add_settings
 - delete_settings

We already had the `browse_settings` so I made sure to add the other ones 👍

**Comment by tnylea** [comment]
Also, I would like to add something for version 1.0,

I would like for each setting key to be saved with a prefix of each group. For instance, let's say that we had a group of `admin` and we then created a new setting called `title`, for this setting to be referenced it would be nice if the user can use the following code:

```php
echo setting('admin.title');
```

I think that would be easier to read and understand, let me know your thoughts :)

Thanks.

**Comment by emptynick** [comment]
I thought about this also, but accessible as an array, so you could do something like this:
`foreach (setting('admin') as $value)`
Could be really useful if you have depending settings (e.g. slides for a slideshow)

The only thing we have to make sure is that the setting-key is unique in the group, not in the whole settings.

**Comment by tnylea** [comment]
@emptynick, yeah totally. That would be amazing. I was thinking that as we save the setting we can prefix it with the group, so it will automatically lowercase the group name (ex 'Admin' => 'admin') and then prefix it with the key, so if you add the key 'title', it will save the key as 'admin.title', I'll be working on this a bit today 👍

**Comment by emptynick** [comment]
No worries, already done it.
Im just trying to figure out how to stay backward-compatible

**Comment by tnylea** [comment]
Ok, cool. Good Idea. We can always add this to the Upgrade Guide. It will be something that users need to update in order to upgrade to the latest version.

**Comment by fletch3555** [comment]
👍

**Comment by emptynick** [comment]
I'm still waiting for your suggestions if the user should be able to change the keys, or if its an permission/config option.

Please let me know, I have 3 versions ready to pull!

**Comment by marktopper** [comment]
Well, if it is going to be possible to change the key, the user should be warned about it, since it can have consequences.
However I don't think it's a completly bad idea to let them change it, we just need to make sure they always get a warning.

**Comment by marktopper** [comment]
Let's start with not having it an option for the user to change the key, we can always add this option later.

Merging in now since the test have been fixed.

**Pull request merged**
