### PR TITLE
Add support for dynamically changing view parameters through events

### PR DESCRIPTION
**Pull request by marktopper**
### Load a view with support for dynamically changing view parameters

```
Voyager::view('voyager::hello', [
    'name' => 'Mark',
]);
```

### Add event to do something when that specific view is loaded

```
Voyager::onLoadingView('voyager::hello', function ($name, array $parameters) {
    // This triggers when the "voyager::hello" view is loaded
});
```

### Change view and/or parameters

```
Voyager::onLoadingView('voyager::hello', function (&$name, array &$parameters) {
    $name = 'something::else';
    $parameters['foo'] = 'bar';
});
```

/ping @akazorg

### CODE REVIEW

**Comment by fletch3555** [comment]
@marktopper, what prompted this? It's somewhat contrary to "the Laravel way"

**Comment by akazorg** [comment]
Great job Mark, testing now.

@fletch3555 this will allow us to load custom views without the need of extending Voyager Controllers. I'm not sure what is the "Laravel way" of doing this, but events sounds a nice approach.
Would you handle it differently?
Please, share your ideas with us.

**Comment by fletch3555** [comment]
I guess I don't understand the need.  What "custom views" would you be loading that would require overriding the controller?

**Comment by akazorg** [comment]
For example, from VoyagerBreadController, at the show() method we have:
```
    public function show(Request $request, $id)
    {
        $slug = $this->getSlug($request);
        ....
        $view = 'voyager::bread.read';

        if (view()->exists("voyager::$slug.read")) {
            $view = "voyager::$slug.read";
        }

        return view($view, compact('dataType', 'dataTypeContent', 'isModelTranslatable'));
}
```
If we want to use a view that doesn't match the BREAD slug, it would require to overwrite the Controller.

**Pull request merged**
