### PR TITLE
Moving form-field rendering to view-partials

### PR DESCRIPTION
**Pull request by fletch3555**
Fix for #200

### CODE REVIEW

**Comment by akazorg** [comment]
Finally!! nice job

**Comment by marktopper** [comment]
Hows the progress with this?

**Comment by fletch3555** [comment]
This is about as far as I'm going to get anytime real soon.  Should be good to go.  Still needs documentation updates

**Comment by marktopper** [comment]
Great job, will test it out.

**Comment by marktopper** [comment]
Works like a charm. However, should this go to `release/v0.11` or `master`?

**Comment by fletch3555** [comment]
I had it in v0.11 because there are significant changes to the views.  If you're thinking it can go into master, by all means, make your case and I'll be fine with it.

**Comment by marktopper** [comment]
I'm also okay with it getting into `v0.11`, I must also do some pulls for that soon.

Merging into `v0.11` right away.

**Pull request merged**
