### PR TITLE
Fix missing permission returning true

### PR DESCRIPTION
**Pull request by emptynick**
Permission returned true if the permission does not exist as mentioned
in #1172 and #1168.
Also inversed the check so function can() only returns true if the user
!= null and the permission is assigned to this user - not vise versa

### CODE REVIEW

**Comment by marktopper** [comment]
The idea is that if a permission does not exists in the system, everyone can actually do it, else even the admin wouldn't have the permission.
I however am open for changing this behavior upon request.

I am opening this for discussion.

**Comment by marktopper** [comment]
I think the best solution would be to throw an exception if the permission does not exists.
And then merge that to v1.

Thoughts @emptynick.

**Comment by akazorg** [comment]
I like throwing an exception.

**Comment by marktopper** [comment]
@akazorg. Me too, I think we should do this for v1.

**Comment by akazorg** [comment]
I've sent PR #1285 for fixing this.

**Comment by marktopper** [comment]
Merged into `v1.0-pre-release`.

**Pull request closed without merging**
