### PR TITLE
Default i18n support

### PR DESCRIPTION
**Pull request by gnovaro**
Add support for i18n in predefined voyager views. And create a default lang file. During installation can be copy resources/lang folder maybe...

### CODE REVIEW

**Comment by abdgad** [comment]
Localization changed a little bit in Laravel 5.4:
http://themsaid.com/laravel-54-localization-json-20161117/
https://laravel.com/docs/5.4/localization

It's better to add it when we drop support for 5.3

**Comment by marktopper** [comment]
This will indeed be nice to have into Voyager.
It will however be needed to be added everywhere for everything in Voyager.

**Comment by marktopper** [comment]
@abdgad: I can easily make a fallback of the `__`-method to support Laravel 5.3.

**Comment by abdgad** [comment]
@marktopper (y) so we can start localizing now and not wait

**Comment by marktopper** [comment]
I have not forgot this.

I however just figured out that currently a package can **not** add JSON translations to a application. Since it only reads JSON translations from `APP-ROOT/resources/lang/*.json`
So I am waiting for a response on this at https://github.com/laravel/framework/issues/17923

**Comment by Frondor** [comment]
Lang files can be publishable tho :D 

> https://github.com/the-control-group/voyager/pull/561#issuecomment-279432799

**Comment by marktopper** [comment]
@Frondor: I see, using the old syntax methods works for the `__`-function.

We have 2 solutions now.

#### Solution A
Wait for Laravel to maybe add support for package specific JSON translations.

#### Solution B
Use PHP array based translation files, but use `__('voyager.key')`.

--- 

Thoughts?

**Comment by marktopper** [comment]
Btw @gnovaro. Love the fact that you sort the listing in the JSON file 👍

**Comment by gnovaro** [comment]
Thanks, Maybe I missed some key.

**Comment by Frondor** [comment]
> Use PHP array based translation files, but use __('voyager.key').

And I truly believe that performs better than JSON files (when configs are cache'd).

**Comment by marktopper** [comment]
Lets do it that way @Frondor.
Then to support the underscore method in Laravel 5.3
```
if (! function_exists('__')) {
    function __() {
        return call_user_func_array('trans', func_get_args());
    }
}
```

**Comment by gnovaro** [comment]
@marktopper Do you want to make a branch for this.. maybe my neighbor @Frondor want to help me to translate the app to spanish to. I need update the json strings with the #745 and #752

**Comment by gnovaro** [comment]
@Frondor your are right for me is better in php than json... and we cant implent this feature sooner

**Comment by marktopper** [comment]
Created branch `i18n`.

**Comment by fletch3555** [comment]
@marktopper, can you please provide an update on the status of that i18n branch and whether this can be merged or closed?

**Pull request closed without merging**
