### PR TITLE
Register dependency providers in VoyagerServiceProvider

### PR DESCRIPTION
**Pull request by jorenvh**
Register the intervention/image service provider from in the VoyagerServiceProvider. 
Users of the package don't have to register that provider manually anymore.

I also removed the provider in the installation instructions in the readme.md file.

### CODE REVIEW

**Comment by tnylea** [comment]
Thanks man. I'll merge this in. Quick question though, wouldn't we want to add the Voyager Service provider to be automatically included as well? Let me know :)

Thanks.

**Comment by jorenvh** [comment]
@tnylea that's not possible the voyager provider is the main provider for your package, you can only do that for your dependencies. Otherwise your provider will never be loaded.

**Comment by maiorano84** [comment]
@jorenvh That's correct, Service Providers cannot be self-loading. I like the fact that the Intervention dependency is included with the primary Voyager provider.

I'm wondering, since I haven't tested this myself:

If the Intervention library has already been loaded by a previously-declared library, would that necessitate a check to see if the library has already been loaded? Or would Laravel skip over it, recognizing that it's already been registered?

**Comment by jorenvh** [comment]
@maiorano84 good question! I haven't taught about that, we should test that indeed. However I used this code before in my own packages or services within Laravel and there was no issue reported about this.

But we should definitely test that use case.

**Comment by arcanedev-maroc** [comment]
@tnylea This is a duplicated PR: #142

**Comment by jorenvh** [comment]
@arcanedev-maroc I didn't check for an existing PR, sorry for that. 

Still think my solution is more future proof, when there are more dependencies you only have to add them to the providers array, so less duplicate code.

**Comment by arcanedev-maroc** [comment]
@jorenvh Yeah i agree but for the time being it has one dependency that you need to register its service provider.

And my solution has less code (1 line) then your solution. 😉

**Comment by jorenvh** [comment]
@arcanedev-maroc fair point ;)

**Comment by jorenvh** [comment]
Since this is a duplicate for PR: #142 and their is only one dependency at the moment you can better use the solution provided by @arcanedev-maroc.

**Pull request closed without merging**
