### PR TITLE
Fix for perfect scrollbar

### PR DESCRIPTION
**Pull request by davodavodavo3**
Fix for perfect scrollbar that doesnt appear on admin side menu
Reference issue #1744

### CODE REVIEW

**Comment by tnylea** [comment]
@davodavodavo3 Thans man!

**Comment by davodavodavo3** [comment]
@tnylea why guys commented file types in media manager
```
<!--template v-if="selected_file.type.includes('audio')">
                                                <audio controls style="width:100%; margin-top:5px;">
                                                    <source :src="selected_file.path" type="audio/ogg">
                                                    <source :src="selected_file.path" type="audio/mpeg">
                                                    Your browser does not support the audio element.
                                                </audio>
                                            </template>
                                            <template v-if="selected_file.type == 'folder'">
                                                <i class="voyager-folder"></i>
                                            </template>
                                            <template
                                                    v-if="selected_file.type != 'folder' && !selected_file.type.includes('audio') && !selected_file.type.includes('video') && !selected_file.type.includes('image')">
                                                <i class="voyager-file-text-o"></i>
                                            </template-->
```
Do you know?

**Comment by davodavodavo3** [comment]
I'am fixing media manager issue when double click on image he think that its an folder,
and I stumbled in this code

**Comment by fletch3555** [comment]
@davodavodavo3, that is unrelated to this issue.  Please try to keep the comments relevant

**Comment by fletch3555** [comment]
@davodavodavo3, that is unrelated to this issue.  Please try to keep the comments relevant

**Comment by davodavodavo3** [comment]
Where i can ask you questions?

**Comment by fletch3555** [comment]
Slack would be a good place to do that

**Pull request merged**
