### PR TITLE
Fixed media manger double click issue and enhancements

### PR DESCRIPTION
**Pull request by davodavodavo3**
1. Fixed double click and enter keypress issue on files that are not a folders.

2. Added modal image view on double click and enter keypress.

3. Uncommented file types in media index file for watch and listen video and audio files.

4. Fixed breadcrumbs  that are not clickble for next paths(dynamically add media_breadcrumb class for non last child breadcrumb).

5. Commented console loooogs))

6. Now media manager support uploading a gif images with animation. like this

voyager-gif

7. Added backspace key for go back to previous folders.If whe are in root folder it also will refresh media manger.We can prevent that if we want

8. Fixed issue when two folders have same name. Example:
I have one folder called April2017, and other one inside it called new, and other folder inside new folder called new)))) When you double click on folder new that's inside new folder in breadcrumb show April2017 instead of new. And if you upload something it's will be in April2017 folder not in second new folder.

9. Added dateFilter method to show human date in last modified field. Like this 
Last Modified:2017-09-20 3:22:01

10. Now you can upload what you want, there will be no errors and file will be correctly moved to final destination. Images as old functionality will be unique renamed, other files will be uploaded with original name( can be changed if we need  ).
And maybe for security reason we'll want to upload only certain types of files(in future maybe add validation).

11. Added voyager-archive icon to zip archives and voyager-music to music files.

Now seems media manager doesn't have any issues))))

### CODE REVIEW

**Comment by davodavodavo3** [comment]
##  We will overcome all obstacles Voyager
<div align="center">

</dvi>

**Comment by davodavodavo3** [comment]
Tony do you like the enhancements and fixes?

**Comment by davodavodavo3** [comment]
Issue #1745 is fixed
Uploading an SVG is fixed issue #315
Uploading PDFs is fixed issue #393

**Review by marktopper — APPROVED** [review]
Tested and works like a charm

**Comment by fletch3555** [comment]
@davodavodavo3, please resolve the conflicts and we'll get this merged in.  Thanks!

**Comment by davodavodavo3** [comment]
@fletch3555 can you resolve conflicts?
@marktopper will resolve them tomorrow

**Comment by davodavodavo3** [comment]
Conflicts are resolved

**Comment by davodavodavo3** [comment]
@marktopper there is several line of code that I will refactor in next update, for now merge this , I will create new PR with image crop functionality In a few hours

**Comment by marktopper** [comment]
Thanks @davodavodavo3.

**Pull request merged**
