### PR TITLE
Basic I18n working in progress

### PR DESCRIPTION
**Pull request by gnovaro**

### CODE REVIEW

**Comment by marktopper** [comment]
Can you please check that when using this, then the login button contains the text `Login`.
Since TravisCI complains about that.

**Comment by marktopper** [comment]
Create work here, I have not forgot this. I just need to make the last tweaks to support this 👍

**Comment by akazorg** [comment]
great job @gnovaro! 
what's the status of this?
@marktopper ping me if I can do any help with this.

**Comment by marktopper** [comment]
Due to the facts that Laravel will not fully support JSON translations from packages we have decided to go ahead and implement the old method for translations.

**Pull request closed without merging**
