### PR TITLE
Improve the installation process

### PR DESCRIPTION
**Pull request by abdgad**
The goal of this PR is to improve the installation process and add more options etc... See #492

In order to organize Installation commands and make it easier to add new options in the future etc... I created a special namespace for Installation related commands.
Did some refactoring to **InstallCommand** to make it easier to add more installation options in the future.
Created **Settings.php** which should contain required settings for installation. Currently it also contains some helper methods. I didn't know where to put them, so I just added them there...

- [X] When installing, check if there is an existing installation. warn the user.
- [X] Added installation options for the user in case there is an existing installation.
- [X] Add command to uninstall Voyager.
- [x] Find a way to reset only Voyager migrations when uninstalling.
- [x] Copy Voyager publishable resources to a special folders to delete them easily when uninstalling.
- [ ] Decide whether to rollback Voyager migrations during uninstallation, or leave to it to the user to do it manually. Cause if the user has migrations that build on top of Voyager ones, it may cause issues if we remove them.
- [ ] Add command to backup existing installation.

Please give us your suggestions = )

### CODE REVIEW

**Comment by marktopper** [comment]
Just noticed that you added `UserTableSeeder` even if `--with-dummy` is not defined.

The thing is we need a way to *not* create a user, since some people might want to add Voyager to their existing Laravel application.

**Comment by abdgad** [comment]
Ok I just reverted that = )

**Comment by marktopper** [comment]
@abdgad: However if you have another idea for a way to choose wether or not to create a user, I am open minded. :)

**Comment by abdgad** [comment]
@marktopper To login to Admin Area, a user is required, right? So I think it makes sense to create a default admin account even if --with-dummy is not specified since it's a required thing. What do you think?

**Comment by abdgad** [comment]
The main features of this PR are ready. Please test and give me suggestions to make more improvements = )

**Comment by abdgad** [comment]
Just noticed that there is a --path option for migrate command that can be used to migrate and rollback migrations from a specific path. It can be used here. The only problem is that Voyager doesn't ship with a create_users_table migration, and migration using --path will fail because users table is missing.
I suggest shipping a create_users_table migration with voyager. see #497

**Comment by marktopper** [comment]
@abdgad: I can see it could be a good idea to create a user even if `--with-dummy` is not set.
Maybe it could create the user if no users currently exists, if users do already exists, it means that it is an existing application.

Also publishing `create_users_table` would give errors for applications that already have a `users` table. I'm however open for ideas.

**Comment by abdgad** [comment]
@marktopper Here are my suggestions.

1) Add a table_prefix: this is a prefix that Voyager tables will use. For example 'voyager_menus'. This will set apart Voyager specific tables from the rest.
2) When installing, prompt the user to enter his user Model. We will offer him a default one.
    Add the user Model to voyager.namespace config. This is where custom user model is stored, right?
    Please tell me which User model is used cause I am a bit confused here.
3) Include a create_users_table migration: It will use the table name from specified user model, and it only creates a users table if it doesn't exist.
4) If --with-dummy is not specified, migrate only core tables that are required for Voyager to function. Tables like categories and posts are not core tables.
5) Seeds: if --with-dummy is not specified, only seed core data. No demo stuff.
    Also seed a user account if one doesn't exist.
6) If --with-dummy is specified, migrate dummy tables and seed them.

I think these steps will deal with users table issues and also make it cleaner to install and uninstall voyager.
Please tell me what you think?

**Comment by marktopper** [comment]
1. We could add a table prefix, but it should be optional, as not everyone would like this.

2. Asking for the user model could be a good option. And then fallback to `voyager.user.namespace` if not defined.

3. Yes, `voyager.user.namespace` is the ideal User model.

4. Indeed, it would be nice to leave those migrations out.

5. Seeding of user account if NONE exists could be fine with me.

6. 👍

**Comment by marktopper** [comment]
About your todo:
> Decide whether to rollback Voyager migrations during uninstallation, or leave to it to the user to do it manually. Cause if the user has migrations that build on top of Voyager ones, it may cause issues if we remove them.

Maybe we should ask the user if they wish to rollback and let it be up to them on uninstall?

**Comment by marktopper** [comment]
Would you be able to split up the features for the backup command?
> Add command to backup existing installation.

Since I would love to help building this, just wish to know what parts you would backup how. 😄

**Comment by abdgad** [comment]
@marktopper I think we should continue working on installation after Voyager is stable. Then, we'll know which things to backup etc...

**Comment by fletch3555** [comment]
I'm closing this for now.  We can revisit it after a v1.0 release

**Pull request closed without merging**
