### PR TITLE
Fix for JSON options that cannot be updated in BREAD.

### PR DESCRIPTION
**Pull request by davodavodavo3**
Small css addon that change caret when you collapse dropdown in left menu.

Fix for JSON options that cannot be updated in BREAD.

### CODE REVIEW

**Comment by abdgad** [comment]
Note: please create separate PRs for each feature/change you want to make, so we can review them easily.

**Comment by davodavodavo3** [comment]
yes ,I'm sorry,  this is my  mistake

**Comment by akazorg** [comment]
Hi @davodavodavo3 what is the status of this? Thanks!

**Comment by davodavodavo3** [comment]
As far as I remember everything works fine. But i dont test it with last version ,
I think the admin is improving very slowly, and I no longer follow the development

**Comment by akazorg** [comment]
@davodavodavo3 You've mixed different subjects on the same PR, have you fixed that? (as @abdgad mentioned).

Please let us know if you have abandon this PR so we can sort this out.
Thanks!

**Pull request closed without merging**
