### PR TITLE
fixed plugin datetimepicker

### PR DESCRIPTION
**Pull request by alexeykostenko**

### CODE REVIEW

**Comment by fletch3555** [comment]
So.... what is this fixing...?

**Comment by fletch3555** [comment]
dupe of #1562 and #1563?

**Comment by alexeykostenko** [comment]
At the moment, the plugin datetimepicker does not work in the master branch, I fixed it

**Comment by fletch3555** [comment]
It looks like the "fix" isn't a fix, it's a replacement to use a different plugin.  Was there an issue that this is fixing? I have no context here.  What was the original issue?

**Pull request closed without merging**
