### PR TITLE
Debug date validation (BREAD)

### PR DESCRIPTION
**Pull request by nicolaszanghi**
Hello,

I have a Date field that is required :

screen shot 2017-12-06 at 18 49 25

But when I tried to create a new entry, I had this error in the console, and nothing append :

screen shot 2017-12-06 at 18 51 37

I find that in the validation is the display_name that is used, so "Date" and not "date". So the validation was not working.
I think that would make more sense to use the field instead of the display_name and in the JS to use "name=" instead of "data-name=".

I'm a new user of voyager, so let me know if I'm wrong :)

### CODE REVIEW

**Comment by fletch3555** [comment]
This is more complex than simply changing those fields. Also, I swear we already fixed this... or at least have a PR open to do so.  @akazorg @emptynick, are either of you guys familiar with this?

**Comment by fletch3555** [comment]
Same or similar PRs that are currently open: #2191 #2198

**Comment by akazorg** [comment]
Hi @fletch3555, I don't know about this. 
I'll have more time next week, I'm quite busy atm.

**Comment by blitux** [comment]
I've sent a PR to fix this on nov 8th. Is there something I can do for the PR to be merged? There was a release a few days ago and the opportunity for this fix to be released was lost.

**Comment by akazorg** [comment]
Thank's for the note @blitux, we've been busy. It should merged soon.

**Comment by fletch3555** [comment]
The PR @blitux mentioned above (#2191) was closed nearly a month ago (superseded by #2660), so I'm closing this one.

**Pull request closed without merging**
