### PR TITLE
Support Enum

### LINKED ISSUE #1766: php artisan migrate:refresh returns error on fresh install
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version:
- Database Driver & Version:

### Description:

After a fresh install of Laravel and Voyager, if I try to run `php artisan migrate:refresh` it returns error.

```
php artisan migrate:refresh --seed


  [Doctrine\DBAL\DBALException]
  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.
```

### PR DESCRIPTION
**Pull request by marktopper**
Add support for `enum` for MySQL
Reference: larapack/doctrine-support@02c9fc7
Fixes #1766

### CODE REVIEW

**Comment by DaKe-Zhang** [comment]
hi Mark

not sure about this, but this is still not working, right?

btw, the update to larapack/doctrine-support:v0.1.4 right? not v1.0.4

**Comment by marktopper** [comment]
What seems to be the issue @DaKeZhang7412?

**Comment by DaKe-Zhang** [comment]
image

It seems still saying that ENUM is not supported.

When I tried to created property for a new table, the ENUM is NOT selectable.

**Comment by BeetleJ** [comment]
Any update on this issue?

**Comment by Bokijac** [comment]
Yes, I also have same issue, even after update to "larapack/doctrine-support": "0.1.4",

**Pull request merged**
