### PR TITLE
[WIP] Add RTL support

### PR DESCRIPTION
**Pull request by marktopper**
**Work in progress**

This is going to add RTL (Right To Left) support.
Enable RTL support
```
Voyager::rtl();
```

### Current progress
skaermbillede 2017-02-21 kl 21 25 40
skaermbillede 2017-02-21 kl 21 05 55

### CODE REVIEW

**Comment by mustafa-qamaruddin** [comment]
Wow! Great Progress...

Are all strings translatable via trans('') function?

**Comment by marktopper** [comment]
Thanks @thecortex.

No, the strings will become translatable later in another pull request via the `trans()` function.

**Comment by sinaboromand** [comment]
Aweeesomeee @marktopper

**Comment by marktopper** [comment]
I will hopefully have time to do some other pages today.
Will share the progress.

**Comment by marktopper** [comment]
There is an issue with the login page background size, anyone have an idea how to fix this?

**Comment by marktopper** [comment]
Merged from #838

**Comment by fletch3555** [comment]
@marktopper, I'm jumping in a little late here.  What does this do that CSS alone couldn't do?

**Comment by marktopper** [comment]
@fletch3555 It is a new CSS file.

**Comment by fletch3555** [comment]
I stand corrected.  I saw the `isRTL()` function and thought it was doing more than it is.  Carry on!

**Comment by fletch3555** [comment]
Is this still in progress? There are a number of merge conflicts right now, and no status updates in 2 months

**Comment by faghihi** [comment]
how can we use this feature ? 
thank you already

**Comment by mustafa-ramax** [comment]
This is really amazing work, please how can we use it?
@marktopper

**Comment by marktopper** [comment]
Before I can merge this into `master`.
I need people's feedback if it's good enough.

You can test it out by updating `composer.json` to have the following line:
```
"voyager": "dev-feature/rtl-support"
```
Then run `composer update`

Looking forward to your feedback.

**Comment by mustafa-ramax** [comment]
I tried to add "voyager": "dev-feature/rtl-support" in composer.json but I dont the following error:


> c:\xampp\htdocs\voyager>composer update
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package voyager could not be found in any version, there may be a typo in the package name.
> 
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
> 
> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by marktopper** [comment]
Whats the content of your Composer.json file now?

**Comment by Steve-sy** [comment]
@marktopper here is my Composer.json for now,

`{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "tcg/voyager": "^0.11.12",
        **"voyager": "dev-feature/rtl-support"**
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}
`

**Comment by mustafa-ramax** [comment]
@marktopper here is my Composer.json for now,

> {
>     "name": "laravel/laravel",
>     "description": "The Laravel Framework.",
>     "keywords": ["framework", "laravel"],
>     "license": "MIT",
>     "type": "project",
>     "require": {
>         "php": ">=5.6.4",
>         "laravel/framework": "5.4.*",
>         "laravel/tinker": "~1.0",
>         "tcg/voyager": "^0.11.12",
>         "voyager": "dev-feature/rtl-support"
>     },
>     "require-dev": {
>         "fzaninotto/faker": "~1.4",
>         "mockery/mockery": "0.9.*",
>         "phpunit/phpunit": "~5.7"
>     },
>     "autoload": {
>         "classmap": [
>             "database"
>         ],
>         "psr-4": {
>             "App\\": "app/"
>         }
>     },
>     "autoload-dev": {
>         "psr-4": {
>             "Tests\\": "tests/"
>         }
>     },
>     "scripts": {
>         "post-root-package-install": [
>             "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
>         ],
>         "post-create-project-cmd": [
>             "php artisan key:generate"
>         ],
>         "post-install-cmd": [
>             "Illuminate\\Foundation\\ComposerScripts::postInstall",
>             "php artisan optimize"
>         ],
>         "post-update-cmd": [
>             "Illuminate\\Foundation\\ComposerScripts::postUpdate",
>             "php artisan optimize"
>         ]
>     },
>     "config": {
>         "preferred-install": "dist",
>         "sort-packages": true,
>         "optimize-autoloader": true
>     }
> }
>

**Comment by faghihi** [comment]
@marktopper where should we add voyager::rtl() ??

**Comment by faghihi** [comment]
@marktopper by the way I get the exact error written by @Steve-sy when I try to add this feature

**Comment by marktopper** [comment]
@Steve-sy, sorry for misleading you.

Try this for your `require` section of your `composer.json` file:
```
	"require": {
		"php": ">=5.6.4",
		"laravel/framework": "5.4.",
		"laravel/tinker": "~1.0",
		"tcg/voyager": "dev-feature/rtl-support"
	},
```

**Comment by marktopper** [comment]
@faghihi, use that code in your service provider, middleware or controller to enable this.

**Comment by faghihi** [comment]
I checked and this is ok 
can you merge it ? 
I have to use it in a project very soon and as far as I checked this is ok

**Comment by faghihi** [comment]
@marktopper  there is 2 problems 
1. in database tables page the icons are on the table names 
2. the tables which have many columns are not scrolled in the page showing all tuples in table

**Comment by marktopper** [comment]
@faghihi Can you share some screenshots so that I can fix the issue and then we can hopefully get it into the master.

**Comment by alibeheshtian** [comment]
1. When I click on the profile, the drop-down is on the left side
https://cl.ly/3X3Y3z2f030e

2. in Media link "close" on Title "Media Library"
https://cl.ly/082G3Q0X231c

3. post and page "Post Detail" be to left side  
https://cl.ly/2V2i0M1B181p

**Comment by vahid-vahid** [comment]
Hi
I set $rtl=true
but the output i get is not as you showed...
capture

**Comment by faghihi** [comment]
@marktopper  what do you need for merging this into master ?! 
more test ?!

**Comment by marktopper** [comment]
This was almost finished for v0.11.x, however the redesign for v1.0 conflicted with this, so I might have to redo most of the implementations.

**Comment by faghihi** [comment]
let me know if I can help

**Comment by mbdwey** [comment]
@marktopper 
I create new channel called `rtl` on slack to discuss this 
I will try to merge all implementations from v0.11.x to v1.0

**Comment by khalilst** [comment]
Is this fork compatible with Laravel 5.5?
I couldn't install it. There are some errors related to version compatibility after composer update.

**Comment by fletch3555** [comment]
No it's not.  I'm going to close it for now.  Someone else started a new one which IS 5.5 compatible

**Comment by hamid-ne** [comment]
not install laravel voyager RTl version on laravel 5.5

**Pull request closed without merging**
