### PR TITLE
Creating ability to skip migration and/or seeding on voyager:install

### PR DESCRIPTION
**Pull request by fletch3555**
I've seen a few comments (e.g. #57) about not wanting to run the migration and/or DB seeding as part of the install process.  Here's my proposed stop-gap.

### CODE REVIEW

**Comment by afsardo** [comment]
If you do not run migrations and/or db seed what do you need the install for?

Also voyager only works if the db is migrated + seeded.

Sorry if i'm missing something.

**Comment by Mugluck** [comment]
We may already have a viable users table, and so migration and seeding is unnecessary. Install also builds out the views and pages for Voyager, not just the database side.

**Comment by fletch3555** [comment]
It allows you to only run one or the other.  Perhaps you've already run voyager:install, then modified something and wanted to re-seed the voyager tables, you could run it without re-running the migrations.  Perhaps you're installing it on top of an existing application and don't want to run the migrations.

**Comment by afsardo** [comment]
@Mugluck it's not unnecessary, it needs to migrate all the other tables. I've posted a "work around" (not tested) to that problem at issue #57.

**Comment by afsardo** [comment]
@fletch3555 In all of those cases it's a matter of running those commands individually, basicly what `artisan voyager:install` does is pretty much:
- `artisan vendor:publish`
- `artisan migrate`
- `artisan db:seed`

**Comment by fletch3555** [comment]
@afsardo, while I agree that these command options aren't a necessity, what you posted in #57 is essentially the same as what I posted, but in more steps.  You suggest essentially running the voyager:install steps manually, which is not ideal.  Why should this command exist at all if the only way for it to be flexible is to ignore it and run the steps manually?

**Comment by afsardo** [comment]
@fletch3555 That command exists so you install all the things voyager needs to work, if you make those things "flexible" i think it's much more dangerous. Dunno that's my opinion i understand your point as well ;) So all it comes down is for the Maintainers to decide.

**Comment by Mugluck** [comment]
Might be nice to have an option to add something like -nomigrate to the install commands, just to simplify things, or a few commands for specifying that there is an existing users table, which means the installer only adds the necessary collumns to an existing table. But that's more of an ease of life thing.

**Comment by tnylea** [comment]
@fletch3555 @Mugluck I get what you guys are saying here. There are 2 tables that will need to be migrated though, which are the data_types and data_rows. I can try and add the functionality for this next week, so I'll keep this open until then.

Thanks for the suggestion. I agree it will be needed for users of existing projects.

**Comment by marktopper** [comment]
I think the big problem for users here is not that they do not want to run the migrations, its the seeding they do not like.
I personally do not like seeding for existing projects, however I have no problem seeding data for new projects.
However in this case where the user **needs** to seed the `data_types` and `data_rows` into the database in order to work, I would however force it by using migrations for that instead.
I know that this is against the principles of migrations and seeds, but rules are for being broken, at least a few times.
I however would really appreciate peoples mind on the matter.

**Comment by fletch3555** [comment]
How about we add a command flag such as "essential-only" that only runs migrations/seeds for the essential tables, and not users/posts/etc.?

**Comment by marktopper** [comment]
Wonderful idea @fletch3555!

We can still do it using seeders, however just without publishing them and calling them this way.

```
php artisan db:seed --class="\My\Package\Seeder\MyCustomSeeder"
```

**Comment by marktopper** [comment]
@fletch3555 How about calling the flag `without-dummy` since the posts, categories and users seeders are just for dummy data.

Also, are you gonna do commits to this pull request?

**Comment by fletch3555** [comment]
@marktopper,@tnylea

Sure, I'll update this PR with this change instead of the other one.

`--without-dummy` seems oddly phrased to me.  Can we do `--no-dummy-data` or something instead? Or `--no-seed-sample`? I'm open to other suggestions as well if these spark any ideas.

**Comment by marktopper** [comment]
They sounds good to me 🎉

**Comment by fletch3555** [comment]
Perfect. I'll pick one and let you know when done.

**Comment by fletch3555** [comment]
@marktopper / @tnylea, How's this for an attempt?  I can update the documentation to go with it if you guys approve of this.

You can choose 1 of these options:

1. migrate and seed ALL tables (normal)
2. migrate ALL and only seed essential (`data_types` and `data_rows`) (`--no-dummy-seed`)
3. ONLY migrate and seed essential (`--no-dummy`)

**Comment by marktopper** [comment]
There is no migration of dummy data.
Also the only reason I can see in order that someone might not wish to migrate is because they use the database table already for something else (which just will move the issue to somewhere else) or if they do not wish to use certain parts of Voyager like the menu builder (then the `menus` database table could be left out).
However I personally think that everything should be migrated to ensure that the database matches the requirements, however I wish to separate items like the menu builder from this migration and into another installation. Just like what Laravel does for using the database for storing sessions, in order to do that you must run `php artisan session:table` which will create the table.
What do you think @fletch3555, what's the reason you would not migrate it all?

**Comment by fletch3555** [comment]
I personally was not using the Posts/Pages/Categories features, so I was building it toward importing the minimum necessary.  This is a step toward #147.  Importing only the minimum will prove it can be done, and allow each "Rig" to get built on top of that.

**Comment by marktopper** [comment]
@fletch3555, okay then lets focus on having the install script migrating everything, and seeding dummy data when the flag `--no-dummy` is left out.
Then we can focus on removing certain migrations from the installation and move them into separate commands.

**Comment by fletch3555** [comment]
@marktopper, how's this? Also, I'm not sure why Travis is failing... It doesn't appear to be related to anything I changed.

**Comment by marktopper** [comment]
I will look at whats up with Travis 💪

**Comment by marktopper** [comment]
I merged to a new branch in order to fix the issue with Travis. Will keep you posted.

**Comment by marktopper** [comment]
Merged with TravisCI support at #221

**Pull request merged**
