### PR TITLE
Fix route

### LINKED ISSUE #139: MethodNotAllowedHttpException in RouteCollection.php line 218:
I edit table in ~/admin/database/edit-users-table, and Update table,   I get error.
my voyager is v0.9.2x, Laravle v5.3.16

MethodNotAllowedHttpException in RouteCollection.php line 218:

in RouteCollection.php line 218
at RouteCollection->methodNotAllowed(array('GET', 'HEAD')) in RouteCollection.php line 205
at RouteCollection->getRouteForMethods(object(Request), array('GET', 'HEAD')) in RouteCollection.php line 158
at RouteCollection->match(object(Request)) in Router.php line 780
at Router->findRoute(object(Request)) in Router.php line 610
at Router->dispatchToRoute(object(Request)) in Router.php line 596
at Router->dispatch(object(Request)) in Kernel.php line 267
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
at Pipeline->then(object(Closure)) in Kernel.php line 149
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 116
at Kernel->handle(object(Request)) in index.php line 54

### PR DESCRIPTION
**Pull request by marktopper**
Fix #139

### CODE REVIEW

**Comment by vanloc0301** [comment]
I tried your fix, but it shows error like this:

```
FatalErrorException in VoyagerDatabaseController.php line 210:
Call to a member function nullable() on null
```

But it still working, it edit table name success but show error like this. I must refresh page at routes: `admin/database` to show update is apply.

**Comment by marktopper** [comment]
@vanloc0301 That is a issue with the VoyagerDatabaseController, not the routes.

But I think this happens when you try to manage a table that have a `nullable` column, am I right?

**Comment by marktopper** [comment]
Additional informations on the issue @vanloc0301 is talking about, visit #190.

**Comment by marktopper** [comment]
Closing, since this seems to have been fixed.

**Pull request closed without merging**
