### PR TITLE
Update multiple_images.blade.php

### PR DESCRIPTION
**Pull request by marcelosantos89**
In case of model casting check if its string or array.
This way makes it easier for people to get data from database

Ex: Model\Page.php

public function getImageAttribute($value)
{
    return json_decode($value);
}

### CODE REVIEW

**Comment by marcelosantos89** [comment]
This screws with the browse.blade.php but i can't find a solution for it.

**Comment by fletch3555** [comment]
This feels like the wrong approach, but I can't pinpoint why.  I also don't have a better suggestion at the moment.  Can you describe the problem it's trying to solve for me?

**Comment by marcelosantos89** [comment]
@fletch3555 Lets say you have a table Works and in Works you have image field. In voyager you say that field is multiple images. So far so good. In Work Model using Eloquent i can parse the attributes with getImageAttribute and return json_decode($value) and doing that i don't get the json from the field image but an array with the images to use in Blade. Did you understand? I can provide my source code if you want.

For example to use this image field in blade i have to @foreach(json_decode($works->image) as $image) and i wanted to use @foreach($works->image as  $image) but it's the same. i didn't want to parse data in the view that was all. But it turned out to give me more problems than it helped

**Comment by fletch3555** [comment]
This is old and the original repo seems to have been deleted.  We're going to be refactoring all of the image stuff anyway.  Closing

**Pull request closed without merging**
