### PR TITLE
Search in bread

### PR DESCRIPTION
**Pull request by turtuga**
In other day I see someone request search in bread and I'm trying implement it I dont know if this is the best way but I'm open to suggestions :)

If this is acceptable I will implement in others

ps. forget my tables not styled

### CODE REVIEW

**Comment by fletch3555** [comment]
While I'm sure this would work, I'm not sure I like it.  It's basically doing a full-text search across all fields of the table.  Unless those fields all have indexes, this would be incredibly slow on large tables (many columns OR many rows)

**Comment by akazorg** [comment]
Maybe creating an array at each model, containing all seachable fields?
something like:
`$searchable = ['field_a', 'field_b',...]`

**Comment by turtuga** [comment]
But create an array by hand remove all flexibility of voyager 
Other option I have thinking is in bread we can choose (browse, add, edit, delete) create new option with search

**Comment by Frondor** [comment]
I suggest `filters` instead of this.



With the ability to configure the fields/rows we want from BREAD's details (JSON options)
i.e.:

```js
{
    "searchable": {
        "field_potatoes": { //the fields available to search for as a filter
            "as": "Yummy potatoes", // label for <select> display matters
            "method": "contains", // SQL method for search statement
            "addWhere": { // additional WHERE clauses to make the filter more precise if needed
                "field_tomatoes": "null"
            }
        },
        "field_tomatoes": {
            "as": "Juicy tomatoes",
            "method": "like"            
        }
    }
}
```

**Comment by turtuga** [comment]
Are you implementing this ??

**Comment by Frondor** [comment]
If nobody else does... I can give it a try.

Since I saw this PR I "suggested" what's in my opinion a better approach, but that's it.

**Comment by Frondor** [comment]
Since I saw your PR, I simply gave a suggestion to implement it (imho) in a better way.
If everyone agrees, and you don't  want to address this, I can give it a try.

**Comment by akazorg** [comment]
@turtuga we can save searchable fields on bread options, but we need to think about table indexes (like @fletch3555 mentioned), or queries could get really slow.

There's also [Laravel Scout](https://laravel.com/docs/5.4/scout) to take in mind, it's a great package.

**Comment by turtuga** [comment]
@Frondor I like your suggestion I can try implement it if others agree and if you agree.

@akazorg I don't know these package :( but I take a look at your suggestion and see this `$orders = App\Order::search('Star Trek')->get();` in that way can also be slow in large tables ?

**Comment by Frondor** [comment]
You have to be cautious with Scout because that means end users having to manually  add a trait to their models. Which is not a big deal but I don't know if we want that, because it involves executing a command in order to create the indexes manually. 
We can still use `Artisan::run()` on each BREAD update/save event,  so indexes are created but that's an extra job because you need an interface for enabling/disabling/setting searchable fields... To be honest, that part isn't clear to me right now.
And finally we'd need to create our own driver for voyager, since it doesn't come with other than Algolia one.
So I suggest to try without any package first.

`/admin/bread?filter=field1&q=foo`
Ping the slack if help is needed.

**Comment by marktopper** [comment]
👍 for doing this without the Laravel Scout package.

**Comment by marktopper** [comment]
But just to be sure, are we all agreeing on doing filters?

**Comment by turtuga** [comment]
I agree :)

**Comment by akazorg** [comment]
Hey guys, I just mentioned `Scout` to let some of you know about. I also wasn't thinking on implement this right away.
Search is a missing feature, thought.

Regarding indexes, imho there is always database work involved, users can't expect the search to work magically fast on a huge database, without previously prepare it for so.

**Comment by akazorg** [comment]
hello @turtuga any progress on this?

**Comment by turtuga** [comment]
I'm little busy right now..

**Comment by pboethig** [comment]
What is the progress on this. the missing search is problematic. I think this is a keyy feature. Yoyager makes no sens if you can only fill 100 rows without slowing down everything

**Comment by akazorg** [comment]
@pboethig you're right, this needs to be done. It's one of the priorities.

**Comment by pboethig** [comment]
Cool, thx for feedbacking. Do you have a roadmap on wich we can see when the search for backend paginatiin is comming.

Kind regards

Peter

**Comment by akazorg** [comment]
Hey @pboethig, there's no roadmap atm, but we are working on that.
The search issue will be fixed soon. I personally consider this a priority too.
Happy coding

**Comment by pboethig** [comment]
Thx Bruno. !!

2017-06-16 20:45 GMT+02:00 Bruno Torrinha <notifications@github.com>:

**Comment by AdrianKuriata** [comment]
@akazorg Hi, what do you think about connect laravel-dataTables with voyager? This eliminate problem with slow loading page more than 1k rows, because load is processing on server-side. I actually in work testing this package with 100k rows but i have a problem with searching and query building. If im done with it i can tell you this is good idea and we will implement it to voyager. Server side pagination could be delete.

**Comment by akazorg** [comment]
Hi Adrian, I don't know that package, will have to test it.
I'm sure we need Server Side pagination with the Search feature. Time is needed for this task.

**Comment by AdrianKuriata** [comment]
Laravel dataTables is a dataTables.js package for loading data like a process on the server-side. In dataTables.js you have a search engine. Laravel dataTables working like a normal server side getting rows and pagination but getting data from models with ajax.

**Comment by pboethig** [comment]
Hi Adrian,

I like this datatable project. Its important, that we can modifi the
columns with custom transformer, I think its a good idea to have a look on:
http://dt54.yajrabox.com/eloquent/transformer

The transfomers allows you to use ovveridable views to implement custom
formatters,

It would be great, if you have customization in mind.

What do you think, how long does this approximtly takes on time?

Kind regards

Peter


2017-06-18 10:39 GMT+02:00 AdrianKuriata <notifications@github.com>:

**Comment by akazorg** [comment]
Hello, 

I had a look on DataTables package, it looks great, really!

IMHO, Search should be part of `Voyager Core`, it doesn't make sense to depend on any package.

Please be patience, I'm also missing this feature! :)
Something will come up on the next days.

**Comment by pboethig** [comment]
Hi Bruno,

That sounds very well. I will look forward.
Thanks you very much.

Peter

2017-06-19 2:51 GMT+02:00 Bruno Torrinha <notifications@github.com>:

**Comment by AdrianKuriata** [comment]
@akazorg We talking about searching, i mean things about more than 3k rows and slow loading if our database has to much records. You want do search engine but on the server side option? So sorting by fields won't working? I'm in work, couple minutes ago i did a filtering database with `laravel dataTables`. Everything working perfectly, with 200k records in database loading and sorting working with some miliseconds.

```
public function getCustomData(Request $request)
    {
    	$doles = Dole::query();

    	return Datatables::eloquent($doles)
    	->editColumn('dole_date', '{{date("d.m.Y", $dole_date)}} r.')
    	->editColumn('dole_type', function(Dole $dole) {
    		return $dole->getType();
    	})
    	->editColumn('dole_cash', '{{number_format($dole_cash)}} zł')
    	->filter(function($q) use($request) {
    		if ($request->has('dole_cash_min')) {
    			$q->where('dole_cash', '>=', (int)$request->input('dole_cash_min'));
    		}

            if ($request->has('dole_cash_max')) {
                $q->where('dole_cash', '<=', (int)$request->input('dole_cash_max'));
            }

            if ($request->has('dole_date_min')) {
                $date = strtotime($request->input('dole_date_min'));
                $q->where('dole_date', '>=', $date);
            }

            if ($request->has('dole_date_max')) {
                $date = strtotime($request->input('dole_date_max'));
                $q->where('dole_date', '<=', $date);
            }
    	})->make(true);
    }
```

This is a code for this. Into filter function you can do evrything you want, searching, sorting etc. For this is needed two function, this function is for displaying filtered data, this need JS functions like this
```
if ($("#advance-search").length) {
	var advancedSearch = new Vue({
		el: "#advance-search",
		data: {
			doneTypingInterval: 500,
			typingTimer: null,
			searchUrl: null,
			customDolesData: null,
		},
		methods: {
			drawTable: function() {
				var self = this;
				var minDole = $(self.$options.el).find("[name='dole_cash_min']").val();
				var maxDole = $(self.$options.el).find("[name='dole_cash_max']").val();
				var minDate = $(self.$options.el).find("[name='dole_date_min']").val();
				var maxDate = $(self.$options.el).find("[name='dole_date_max']").val();

				LaravelDataTables["doles-table"] = $("#doles-table").DataTable({
					processing: true,
					serverSide: true,
					ajax: {
						url: self.searchUrl,
						data: {
							dole_cash_min: minDole,
							dole_cash_max: maxDole,
							dole_date_min: minDate,
							dole_date_max: maxDate
						},
					},
					searching: false,
					language: {
						url: 'http://kartoteka.dev/js/Polish.json',
						buttons: {
								copy: 'Do schowka',
								copyTitle: 'Skopiowano do schowka',
								copySuccess: {
								1: "Skopiowano jeden wiersz do schowka",
								_: "Skopiowano %d wierszy do schowka"
							}
						}
					},
					columns: [
						{
							data: 'id', 
							name: 'id',
							title: '#'
						},
						{
							data: 'dole_type', 
							name: 'dole_type',
							title: 'Typ'
						},
						{
							data: 'dole_cash', 
							name: 'dole_cash',
							title: 'Ofiara'
						},
						{
							data: 'dole_date', 
							name: 'dole_date',
							title: 'Data'
						}
					],
					order: [
						[ 
							3, 
							"desc"
						]
					],
					lengthMenu: [
	                	[
	                		10,
	                		25,
	                		50,
	                		100,
	                		150,
	                		1000
	                	],
	                	[
	                		10,
	                		25,
	                		50,
	                		100,
	                		150,
	                		1000
	                	],
	                ],
	                dom: '<"pull-right"B>lfrtip',
	                buttons: {
	                	buttons: [
			                'copyHtml5',
			                {
			                	extend: 'pdf',
			                	text: 'Do PDF'
			                },
			                {
			                	extend: 'excel',
			                	text: 'Do EXCEL'
			                },
			                {
			                	extend: 'csv',
			                	text: 'Do CSV'
			                },
			                'reset',
			                'reload'
		                ],
	                }
				});
			},
			startTyping: function($url) {
				if (this.searchUrl == null) {
					this.searchUrl = $url;
				}

				clearTimeout(this.typingTimer);
				this.typingTimer = setTimeout(this.advancedSearch, this.doneTypingInterval);
			},
			advancedSearch: function() {
				LaravelDataTables["doles-table"].destroy();
				this.drawTable();
			},
		}
	})
}
```

And is required first loading full data function like that:
```
public function add(Request $request, Builder $builder)
    {
    	if ($request->ajax()) {
    		$doles = Dole::with('floor');

    		return Datatables::eloquent($doles)
    		->editColumn('dole_date', '{{date("d.m.Y", $dole_date)}} r.')
    		->editColumn('dole_type', function(Dole $dole) {
    			return $dole->getType();
    		})
    		->editColumn('dole_cash', '{{number_format($dole_cash)}} zł')
    		->make(true);
    	}
    	
    	$doles = $builder->columns([
                [
	                'data' => 'dole_type', 
	                'name' => 'dole_type', 
	                'title' => 'Typ'
                ],
                [
	                'data' => 'dole_cash', 
	                'name' => 'dole_cash', 
	                'title' => 'Ofiara'
                ],
                [
	                'data' => 'dole_date',
	                'name' => 'dole_date', 
	                'title' => 'Data'
                ],
                [
                    'data' => 'floor.floor_name',
                    'name' => 'floor.floor_name',
                    'title' => 'Ulica'
                ]
            ])
    	    ->parameters([
                'language' => [
                	'url' => asset('js/Polish.json'),
	                'buttons' => [
	                	'copy' => 'Do schowka',
	                	'copyTitle' => 'Skopiowano do schowka',
	                	'copySuccess' => [
		                	'1' => "Skopiowano jeden wiersz do schowka",
		                	'_' => "Skopiowano %d wierszy do schowka"
	                	],
	                ],
                ],
                'searching' => false,
                'dom' => '<"pull-right"B>lfrtip',
                'buttons' => [
	                [
	                	'copyHtml5'
                	],
	                [
	                	'extend' => 'pdf',
	                	'text' => 'Do PDF'
	                ],
	                [
	                	'extend' => 'excel',
	                	'text' => 'Do EXCEL',
	                ],
	                [
	                	'extend' => 'csv',
	                	'text' => 'Do CSV',
	                ],
	                [
	                	'reset',
	                ],
	                [
	                	'reload',
	                ]
                ],
                'lengthMenu' => [
                	[
                		10,
                		25,
                		50,
                		100,
                		150,
                		1000
                	],
                	[
                		10,
                		25,
                		50,
                		100,
                		150,
                		1000
                	],
                ],
                'order' => [
                	[
                		3,
                		'desc'
                	]
                ]
            ]);


    	return view('doles.index', compact('doles'));
    }
```

In view we need just put some code like this:
```
{!! $doles->table(['class' => 'table table-striped', 'id' => 'doles-table'], true) !!}
@section('js')
	{!! $doles->scripts() !!}
@endsection
```

This is enougth for create full text search and filtering data whatever you want with fast loading data from database. Thing about it, i hope my code help you take a good decision. I mean dataTables has searching engine so we don't need put searching into filter function unless we expect to searching data by tags or something when is created like ma manytomany relation or something.

**Comment by akazorg** [comment]
Hi Adrian,

I believe dataTables would require quite some time to implement. Plus, we would be creating a dependency on that, and I totally disagree with it.

Other maintainers may have something to say too. I don't decide things in here.

Please be patient :)

**Comment by AdrianKuriata** [comment]
Im just offer, i won't work on it :D

**Comment by tnylea** [comment]
@turtuga Thanks for this. I added the filter functionality in the search as well 👍 

This will be available when we release 1.0 next month :)

search

**Comment by arrilot** [comment]
@tnylea In my opinion filters are the most important feature that is lacking in Voyager atm.
Just my 2 cents:
1. There should be a way to add several filters at the same time
2. It would be great if we could share a link to a filtered list with colleagues

**Comment by joefreire** [comment]
How i can set a field as searchable or not?

**Comment by m7md3omr** [comment]
if implementing DataTables may take time, what is the recommended package to export EXCEL or PDF?

**Comment by fletch3555** [comment]
@corexz, this was merged months ago and has nothing to do with data export

**Comment by froasiooneloop** [comment]
Hi, is this already working?

**Pull request merged**
