### PR TITLE
Improve tables

### PR DESCRIPTION
**Pull request by abdgad**
see #531

- [x] Hide Voyager Core tables from Admin panel by default.
- [X] Add _voyager__ prefix to Voyager tables.
- [ ] Add option to display hidden tables from the Admin panel. Do not allow Edit/Delete actions. Only BREAD actions are allowed.

### CODE REVIEW

**Comment by abdgad** [comment]
@handiwijoyo Hidden Tables will not show by default.
I am thinking to add an option to display them from the Admin panel, but NOT allow edit/delete actions. We just allow to add BREAD to them...
What do you think?

**Comment by marktopper** [comment]
NOTE: This is breaking changes. We need to handle this correctly.

**Comment by abdgad** [comment]
@marktopper we will handle it once we make all the necessary changes.

**Comment by marktopper** [comment]
Is this still relevant or should it be closed?

**Comment by abdgad** [comment]
This should be replaced by newer PR that addresses prefixing Voyager tables.

**Pull request closed without merging**
