### PR TITLE
Add Events Support

### PR DESCRIPTION
**Pull request by akazorg**
(edit)
Adds Event Support to Voyager.
@marktopper is completing tests #1990. This can be used.

Currently is triggering events for the following, (more can be added later):

| Event         | Parameters      | On |
| ------------- |-------------| -----:|
| `BreadAdded` | $dataType, $data |  |
| `BreadUpdated` | $dataType, $data |  |
| `BreadDeleted` | $dataType, $data |  |
| `BreadChanged` | $dataType, $data, $changeType | Bread(Add/Update/Delete) |
| `BreadDataAdded` | $dataType, $data |  |
| `BreadDataUpdated` | $dataType, $data |  |
| `BreadDataDeleted` | $dataType, $data |  |
| `BreadDataChanged` | $dataType, $data, $changeType | BreadData(Add/Update/Delete) |
| `BreadImagesDeleted` | $data, $images |  |
| `FileDeleted` | $path |  |
| `TableAdded` | $table |  |
| `TableUpdated` | $name($array) |  |
| `TableDeleted` | $name(string) |  |
| `TableChanged` | $name(string) |  Table(Add/Update/Delete) |

## How to Use
Please follow the [Laravel documentation](https://laravel.com/docs/master/events#registering-event-subscribers). You can use it by creating your own Listeners, or by listening to a given event at the boot section of the `EventServiceProvider`.

## Example Listening to `BreadDataChanged`

On your `EventServiceProvider`, on the boot() method.
```
    /**
     * Register any events for your application.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();

        Event::listen('TCG\Voyager\Events\BreadDataChanged', function (...$args) {
            // Write some logic here
            // ------------------------------------
            // $args->dataType    ---> TCG\Voyager\Models\DataType
            // $args->data        ---> (Object) Data changed
            // $args->changeType  ---> (String) Added|Updated|Deleted
        });
    }
```

Happy coding!

### CODE REVIEW

**Comment by victorlap** [comment]
This way it would also be really easy to implement a database migration, you can write this data to a file in 'datatase/migrations' and run these migrations on other databases!

**Comment by marktopper** [comment]
Create job @akazorg 🎉 
I will work on some tests now

**Comment by akazorg** [comment]
We do love Events ^^

**Comment by susutw** [comment]
`$args->dataType` doesn't work. It should be `$args[0]->dataType` ! :)

**Pull request merged**
