### PR TITLE
Fix pagination links for server-side searches

### LINKED ISSUE #2217: Server side pagination search issue
- Laravel Version: 5.4
- Voyager Version:1.0.7
- PHP Version:
- Database Driver & Version:

### Description:
htmlspecialchars() expects parameter 1 to be string, array given (View: vendor\tcg\voyager\resources\views\bread\browse.blade.php)

### Steps To Reproduce:
Enable server side pagination.
Go to current bred where it's enabled.
Click on search button then go to the next page(with paginatin)

### PR DESCRIPTION
**Pull request by tenebrousedge**
Should fix #2217

### CODE REVIEW

**Comment by akoSalman** [comment]
Why Voyager does not accept the merge???

**Comment by emptynick** [comment]
This is working fine also.
Tried with a few thousand entries and tried switching filters, pages etc once in a while.

**Comment by fletch3555** [comment]
@akoSalman, it was waiting for one of our QA people (@emptynick in this case) to review it.

**Comment by fletch3555** [comment]
Merging despite TravisCI being unhappy.  The issue was fixed elsewhere and just not pulled into Op's branch

**Pull request merged**
