### PR TITLE
Laravel 5.5

### PR DESCRIPTION
**Pull request by avengerweb**
- [x] Fixed problems with install command
- [x] Dependency updated
- [x] Dev dependencies
- [x] Laravel right way for primaryKey -> getKeyName() 
- [x] Fixed travis build
- [x] Solved problem with multibyte text in widgets image

### CODE REVIEW

**Comment by fletch3555** [comment]
Not sure if you saw, but we already had a 5.5 branch: https://github.com/the-control-group/voyager/tree/laravel-55

I'm sure it's a bit outdated, so yours might be better, but please take a look through there

**Comment by avengerweb** [comment]
I saw it, but its out of date and has only dependency fix, which not works. U will waste time to merge it with master branch. I will keep it updated until laravel 5.5 release

**Comment by marktopper** [comment]
Awesome work, please let us know when it's no longer `Work in progress` 👍

**Comment by avengerweb** [comment]
thx, you are free to merge it :)

**Pull request merged**
