### PR TITLE
BREAD JSON editor & new responsive design for login page

### PR DESCRIPTION
**Pull request by Frondor**
## Contents

- Fix [638#issuecomment-277334908](https://github.com/the-control-group/voyager/pull/638#issuecomment-277334908)
- **Add JSON editor to Database tool.**

- **Login page re-design (way more sexier with material design)**

(actually that's not the default gradient :laughing:, gradient colors can be changed from `config('voyager.login.gradient_a')` or `... gradient_b` )

- Rich text area now shows contents with HTML stripped tags
- Multiple improvements to dashboard UI for small screens UX.
- Dashboard index widgets are now responsive.
- Tables and DataTables are now responsive!!! (even a plugin for [client-side paginated tables](https://i.gyazo.com/fcd420779eb13be7e47d69911353c4f9.gif) can be enabled from voyager's config file)
- Logout is now secured in a POST form.
- Fixed many issues regarding to BREAD `relationship` fields default options
- Fixed `logo` setting. It now displays properly.
- Fixed test case where it was expecting for a fixed value. It now expects the value in your app locale `trans('auth.failed')`
- Moar issue fixes...

### CODE REVIEW

**Review by marktopper — APPROVED** [review]

**Comment by marktopper** [comment]
Great work!
I have moved this to `v0.11`.

Ready to merge when you are 👍

**Comment by Frondor** [comment]
Sure. I'll  create a lititle changelog and see the conflicts, then it shall be ready to merge.

**Comment by marktopper** [comment]
Cool, ping me when ready 👍

**Comment by Frondor** [comment]
@marktopper 

Ok, I think I'm done with that last one commit. Now the question is how shall I resolve those conflicts... I don't have the new structure yet. Probably I'll need to wait for you to implement `Voyager::addFormField()` pull request (?)

~I'll create my change log right now.~
**Change log list done.**

**Comment by marktopper** [comment]
I will hopefully get that done today 👍

**Comment by marktopper** [comment]
#726

**Comment by marktopper** [comment]
Any progress with this?
Let me know if you need help with this :)

**Comment by Frondor** [comment]
I'll try and fix the conflicts once I get in home, later today

**Pull request closed without merging**
