### PR TITLE
Please don't use short tags

### PR DESCRIPTION
**Pull request by gnovaro**
http://softwareengineering.stackexchange.com/questions/151661/is-it-bad-practice-to-use-tag-in-php

### CODE REVIEW

**Comment by marktopper** [comment]
I think it would be better to use `{!! $variable !!}` instead.

**Comment by gnovaro** [comment]
Is the same. I prefer php but is a choise.

**Comment by Frondor** [comment]
It's not the same, it's the laravel way of writting unescaped content https://github.com/laravel/framework/blob/5.4/src/Illuminate/View/Compilers/Concerns/CompilesEchos.php#L42
Personally, I prefer blade syntax over pure php on blade views for obvious reasons. Besides that, blade prepares raw content, unlike simply `<?php echo ... ?>`.
This is a small improvement, but can be turned into a serious coding style problem in future versions.

**Comment by gnovaro** [comment]
@Frondor is and admin, and for this case in particular is a content field. maybe the @marktopper solution is better...

**Comment by Frondor** [comment]
That's what I meant.

**Pull request merged**
