### PR TITLE
Fix typo in translation

### PR DESCRIPTION
**Pull request by IProSoft**
Was: __('generic_successfully_added_new')
Changed to: __('generic.successfully_added_new')

### CODE REVIEW

**Review by akazorg — CHANGES_REQUESTED** [review]
The correct key is `voyager.generic.successfully_added_new`.

**Comment by akazorg** [comment]
Hi @IProSoft, please create separate branches for each issue.
Thank you! :)

**Comment by IProSoft** [comment]
Indeed, my mistake.
Can't understand creating branch for each issue ?

**Comment by akazorg** [comment]
Hello, I'm sorry but we had an issue merging UI changes that shouldn't have been merged.

I mean separate branch for the translation issue, and another for fixing the UI, but I will ask you to wait for response about the UI issue since there's some work in progress. Will let you know soon.
Thanks for the contribution!

**Review by akazorg — APPROVED** [review]

**Review by akazorg — DISMISSED** [review]
Can you please remove this commit? So we can merge this?
UI changes will be pending and it's another issue.
Thank you

**Comment by akazorg** [comment]
Hi @IProSoft, I'm closing this because I've a PR including this correction. Thanks for your work!

About the UI, we will wait for @tnylea to update with the new version.

**Pull request closed without merging**
