### PR TITLE
feature/add-multiple-files-type-field

### PR DESCRIPTION
**Pull request by cloudsben**
save pics field type is TEXT. and JSON data.

### CODE REVIEW

**Comment by marktopper** [comment]
Will test it out and let you know

**Comment by fletch3555** [comment]
I recommend using the name `multiple_images` (or something similar), rather than `multiple_pics`.  `pics` just doesn't sound very professional.

**Comment by marktopper** [comment]
Works like a charm, but could you please rename it to `multiple_images` instead. Sounds better.
Once that is done I will merge this in.

Thanks and great work. 👍

**Comment by cloudsben** [comment]
@marktopper Sorry, but I was enjoying the Spring Festival. I have been renamed it.

**Comment by cloudsben** [comment]
@marktopper  How can I pass StyleCI analysis use .`.php_cs`?

image

**Comment by marktopper** [comment]
You may ignore StyleCI. Fixes are automatically made by StyleCI on merge.

And it seems like they have changed the class for the style fixer config.

**Comment by marktopper** [comment]
Hope you had a great festival!

**Pull request merged**
