### PR TITLE
Allow null values

### PR DESCRIPTION
**Pull request by marktopper**
Possible fix for issue #946.
Have to be tested well before merged.

### CODE REVIEW

**Comment by dimsanchuk** [comment]
I checked. It didn't help.
If the value of the parameter is empty string, then $request->has($row->field) returns false. Therefore, current value is overriten by the previous value.

**Comment by marktopper** [comment]
I see. Doing another commit.

**Comment by marktopper** [comment]
@Dimsanchuk: Can you please test this out again, I will also do some proper testing for this in order to make sure that it didn't break anything else.

**Comment by dimsanchuk** [comment]
@marktopper, It works, but... field must be nullable, else error occurs:

> 1048 Column 'body' cannot be null (SQL: update `blog_posts` set `body` = , `updated_at` = 2017-03-21 19:49:48 where `id` = 3)

I don't know if this decision is correct.

**Comment by dimsanchuk** [comment]
I found, that it is reset all setted images (maybe and files too).
We need to process null values based on the type of field. Separately for text fields and file fields.

**Comment by marktopper** [comment]
Good point @Dimsanchuk.

I will try to make a new commit that handle this.

**Comment by fletch3555** [comment]
@marktopper, any update on this?

**Comment by fletch3555** [comment]
Paging @marktopper.  Any update? Otherwise I'm going to have to close this.

**Comment by marktopper** [comment]
Im going to close this, since it's not yet the perfect solution...

**Pull request closed without merging**
