### PR TITLE
Feature/overwrite models

### PR DESCRIPTION
**Pull request by marktopper**
This allows overwriting the models for Voyager.
I will leave this open for some time so we can discuss whether or not this is a good way to do it.

### CODE REVIEW

**Comment by handiwijoyo** [comment]
@mark can you give some use cases for override the voyager models?

**Comment by marktopper** [comment]
Of cause!

Someone created a issue once where they wanted to use soft delete for data, this can now easily be implemented by extending the models and set the `SoftDelete` trait on the model.

However I'm not sure wether or not to include this feature as it is. So still open for a discussion on wether or not this should be merged.

**Comment by milkmeowo** [comment]
Awesome!
This feature awesome for someone already used `Zizaco/entrust`,`Custom Trait` or anything else
And this feature also can make voyager more flexible

**Comment by fletch3555** [comment]
I'm not sure I agree with this.  What's stopping developers from just subclassing the model in the normal OOP fashion, adding what they need, then just changing the class/package path in the Voyager Database tool?  This would be my preference on how to do it.  I'd prefer to give developers the idea that they can use this without writing any code (too CMS-like, which we're trying to avoid).

**Comment by marktopper** [comment]
Thanks for the discussion.
I have decided to close this.

**Pull request closed without merging**
