### PR TITLE
Adding functionality to generate migration when creating DB table

### PR DESCRIPTION
**Pull request by fletch3555**
Partial implementation of #204.  This creates the migration, but does not populate it with fields.

### CODE REVIEW

**Comment by marktopper** [comment]
It's a good start 👍

**Comment by fletch3555** [comment]
I'm thinking this should be merged as-is, and we can re-implement once we figure a way to build out the fields as well.  It's currently using built-in Laravel functionality to generate the migration.

What are your thoughts @marktopper?

**Comment by marktopper** [comment]
I'm in on that @fletch3555.

We can always add more features for this later on.

**Comment by tokkerbaz** [comment]
Help me with my question =) I'm developing with voyager and want to tell its awesome admin package! Ive never seen cooler adminpack than this =) My question is : 
 I am in development not in production, today i want to publish to internet, and if there is any migration how can i insert to production my custom tables which ive created by voyager? 
Is there any chance that i wont lose tables in production?
Or I should export my local database to hosting? 

Thank you for your work! =)) 
You are making development easier =))

**Comment by marktopper** [comment]
@tokkerbaz, you should copy your database to production.
We will however look forward for having better support for this.

**Comment by handiwijoyo** [comment]
@tokkerbaz Voyager do not have this feature yet. You may want to use this package for now https://github.com/Xethron/migrations-generator

**Comment by vanloc0301** [comment]
Hi @fletch3555 Is that feature continues to develop?

**Pull request merged**
