### PR TITLE
Limit access to the admin area by ip's

### PR DESCRIPTION
**Pull request by davodavodavo3**
You can enable blocker functionality in Voyager config file and block ip's which are not specified in list of ip's.
Blocked ip's can not enter the admin area.
I think will be useful to create maintenance mode switcher in Admin Settings area.
And with allowed ip's user can access site in maintenance mod.
What do you think?

### CODE REVIEW

**Comment by akazorg** [comment]
Great job, I like this idea. Code looks good.
The multiple emojis with your own post - are priceless :D

**Comment by davodavodavo3** [comment]
Thanks @akazorg )))))))

**Comment by davodavodavo3** [comment]
@akazorg can you help me with one question?
#1716

**Comment by fletch3555** [comment]
I'm not sure how I feel about this being in the core... Seems like a great Hook though.

In either case, the whitelist config should be an array of strings, not just a string.  You shouldn't be calling `explode(",")` on that config, it should be presented to you appropriately.

We'll discuss this and get back to you

**Comment by davodavodavo3** [comment]
Good come back do not be shy)))))
Change it to array and call in_array, all fine.
This is for the security of the admin from spam and other similar and not similar attacks.
Online shop's, web sites with payments ,user wallets in databse, or privat pornographic web site created on voyager))).
This is little security candy.))))

**Comment by fletch3555** [comment]
We've discussed this, and believe it would be best built as a hook instead. https://larapack.io/

Thank you!

**Comment by davodavodavo3** [comment]
@fletch3555 how to crate hook?
I cant install any hooks from https://larapack.io/.
If i try it show me
```
Could not find package voyager-polls at any version for your minimum-stability (stable). Check the pac
  kage spelling or your minimum-stability
```

**Comment by fletch3555** [comment]
@davodavodavo3, that's an unrelated issue that should be opened as it's own issue

**Comment by davodavodavo3** [comment]
@fletch3555 there is an open issue in voyager-polls, but no one answered

**Pull request closed without merging**
