### PR TITLE
Add css rule for left menu arrows

### PR DESCRIPTION
**Pull request by davodavodavo3**
Added css rule that will change the left menu arrows to up and down on multilevel menu on open and  close state.

### CODE REVIEW

**Comment by marktopper** [comment]
Can you please run it so we can include the modified minified `app.css` file?

**Review by marktopper — CHANGES_REQUESTED** [review]
Can you please run it so we can include the modified minified `app.css` file in this PR.

**Comment by davodavodavo3** [comment]
i dont have master version of Voyager, and cant run it, I add this in  my 0.11.14 version in css file.

**Comment by marktopper** [comment]
Okay, I will take a look at it then

**Comment by tnylea** [comment]
I'll merge this in and then do a build with this style in another PR 👍

**Pull request merged**
