### PR TITLE
All DB Drivers Proposal: Add SQLite driver compatibility. (Not PR ready)

### PR DESCRIPTION
**Pull request by afsardo**
First pull request for Proposal #30 

Conditionally get all tables from DB according to connection driver.

### CODE REVIEW

**Comment by jaysudodeveloper** [comment]
is there a status on this, i only have the option to use sqlite and would like to use voyager as other alternatives are not up to date.

**Comment by afsardo** [comment]
Some functionality isn't supported for other DB's but all the pending commits were merged.

I'll be working in making it compatible with the other 2 db systems.

**Comment by jaysudodeveloper** [comment]
@afsardo is it an easy change? reading through the issues related around this it seems that voyager was hard coded for MySQL? Are there tests i can run and try to make a work around myself until a compatible release comes.

**Comment by afsardo** [comment]
@jaytheking It is not hard, but not a fast "change".

For the "Get all tables" i extracted it myself and added a static class that resolves the db driver you are using and fetch them accordingly.

https://github.com/the-control-group/voyager/blob/master/src/Facades/DBSchema.php

This is the Facade you should try and implement and change where the queries for db schema logic is hardcoded.

**Pull request merged**
