### PR TITLE
Add new entities on dashboard with setting

### PR DESCRIPTION
**Pull request by bestmomo**

### CODE REVIEW

**Comment by marktopper** [comment]
Please describe what this would do

**Comment by bestmomo** [comment]
On dashbord there are 3 entities 
- users
- posts
- pages

When we add new entities they dont come on dashbord and the view is in package, I didn't try to override it.
I think it would be interesting with a simple config setting to add them on dashbord (example : http://laravel.sillo.org/wp-content/uploads/2017/01/Capture-82.png).

**Comment by marktopper** [comment]
I see, good idea 👍

**Comment by marktopper** [comment]
I marked this as open for discussion since this can be done in multiple other ways.

I will try to think about the best solution for this.

**Comment by bestmomo** [comment]
Sure there are many ways to do that.

**Comment by marktopper** [comment]
I think this is fine for now.

Before I merge this in, we must fix the TravisCI issue.

**Comment by bestmomo** [comment]
Looks like it doesn't like my comments...

**Comment by marktopper** [comment]
Whoops, wrote `CSS` instead of `Config` in my last commit. 😂

Well, hopefully this will fix the TravisCI issue.

**Comment by marktopper** [comment]
We can ignore StyleCI, that will automatically be fixed on merge.

**Comment by marktopper** [comment]
Seems to be fixed, merging in.

**Comment by marktopper** [comment]
This needs to be documenated

**Comment by bestmomo** [comment]
Is documentation in a repo ?

**Comment by marktopper** [comment]
We have the documentation [here](https://github.com/the-control-group/voyager/blob/gh-pages/docs/v0.10/Readme.md) in branch `gh-pages`.

However, if you can not figure it out I will do it 👍

**Comment by bestmomo** [comment]
Done with this commit : https://github.com/the-control-group/voyager/pull/631

Hope my english is not so bad :)

**Comment by marktopper** [comment]
I will go through it later 👍 
Thanks

**Comment by fletch3555** [comment]
@bestmomo, can you update this (add a new PR) to include the config for the existing three blocks and remove them from the view? I'd like to simplify it so it's either all hard-coded, or all handled by a loop.

Thanks!

**Comment by bestmomo** [comment]
I was thinking about something like that but I must dig a bit because of icon and grid system. And there is a bug on route...

**Pull request merged**
