### PR TITLE
FIX - env function call in routes.php

### PR DESCRIPTION
**Pull request by YannikFirre**
Hello,

I propose not to use env() in routes but config().

### CODE REVIEW

**Comment by marktopper** [comment]
There is a reason for the madness.

I reviewed it here as well #106

**Comment by YannikFirre** [comment]
@marktopper Yeah, i understand in local but if you don't use the .env file in production, all is broken :'(

My use case : i put .env in production first time, i execute artisan config:cache then i delete the .env file.

**Comment by marktopper** [comment]
I agree that the current solution does not work perfectly, but neither does this one.

I however can not figure out what a perfect solution would look like.

**Comment by marktopper** [comment]
I myself would prefer a try-catch instead of this.

**Comment by YannikFirre** [comment]
Sorry, but i don't understand in what situation it doesn't work perfectly ? :P 

`config('database.default') = env('DB_CONNECTION', 'localhost')`

**Comment by marktopper** [comment]
The thing that #106 tries to do, is to only run the database call in routes if the system have been installed. However this is the case when `env('DB_CONNECTION')` is not `null`. However doing the using `config('database.default')` will never return `null`, not even when Voyager have not been installed.

**Comment by marktopper** [comment]
Closing, however still looking for another to handle this.

**Pull request closed without merging**
