### PR TITLE
Feature / router setting only from config file

### PR DESCRIPTION
**Pull request by maxkrasnov**
- router setting only from config file
- remove from install command add ['prefix'=> 'admin'] in routes/web.php

### CODE REVIEW

**Comment by emptynick** [comment]
This **WILL** break existing installations.
`routes/voyager.php` will be replaced,
but the install-command will not remove the prefix.
Then you have doubled-prefixes /admin/admin

**Comment by fletch3555** [comment]
Agreed.  I can't let this in `master`.  We'll have to come up with a way to resolve this going forward.  I think we can get it into 1.1 with an upgrade guide stating to remove the group in your `routes/web.php`

**Comment by emptynick** [comment]
This will be fine if there was an UpgradeCommand.
But dont make it harder than it is.
```
$old_route = "\n\nRoute::group(['prefix' => 'admin'], function () {\n    Voyager::routes();\n});\n";
$new_route = "\n\nVoyager::routes();\n\n";
$filesystem->put(base_path('routes/web.php'), str_replace($old_route, '', $routes_contents));
$filesystem->append(base_path('routes/web.php'), $new_route);
```

Written in here - not tested

**Comment by maxkrasnov** [comment]
@emptynick, @fletch3555 check solution:
installer check exist `Voyager::routes()` and remove them from routes/web.php, after we check construction prefix "admin" and if empty, remove it. And after again append `Voyager::routes()`.

Sorry my English :)

**Comment by emptynick** [comment]
You dont run the InstallCommand (`php artisan voyager:install`) if you just update from `1.0.*` to `1.0.*`
Just try setting-up a fresh voyager installation, then check-out your branch `"tcg-voyager": "dev-master#b5099ad"` and try accessing voyager ;)

**Comment by maxkrasnov** [comment]
@emptynick if i'm have few constructions in group for prefix "admin"? we will duplicate the code `Voyager::routes()`

**Comment by emptynick** [comment]
I dont understand what you mean.
The only way to fix it to get it into v1.0 is to check if theres already an admin prefix in `routes/voyager.php` and if yes - dont use `'prefix' => config('voyager.prefix')`.

**Comment by fletch3555** [comment]
I'm going to close this.  The `voyager.prefix` config entry has been removed going forward.  The only thing Voyager should care about is it's current path, and all URLs should be based on that.  That path is defined by the "prefix" given in the `Route::group()`, which I would like to keep in `routes/web.php`

**Comment by maxkrasnov** [comment]
Are you sure this is the right solution? in two places the paths are stored, why not store in one configuration file on param prefix?

**Comment by emptynick** [comment]
Because you have your routes defined in `routes/x.php`.
This should be the only place where routes are imo.

**Comment by fletch3555** [comment]
Because we're refactoring-away those two places.  The route file will be the only instance.

**Pull request closed without merging**
