### PR TITLE
Fix route parameter

### PR DESCRIPTION
**Pull request by AdrianKuriata**
I added some statements and now i didn't get a error, so i think it looks fine. If it is possible, please for someone to test it.

@marktopper 
#1342

### CODE REVIEW

**Comment by vaggelis2018** [comment]
Still getting this error on browser console for url and route parameters. Can't edit or add new item 
TypeError: can't assign to properties of (new String("Dashboard")): not an object  multilingual.js:124:25
@marktopper 
#1342 #1343

**Comment by AdrianKuriata** [comment]
I just repaired error with json_decode like a object given, im not working on multilanguage.

**Comment by tnylea** [comment]
Thanks, Adding this in now :)

**Comment by abkiran** [comment]
I fixed this by running `php artisan view:clear`

**Pull request merged**
