### PR TITLE
Add hook permission

### PR DESCRIPTION
**Pull request by marktopper**

### CODE REVIEW

**Comment by fletch3555** [comment]
This should probably be added to the Hooks package instead, so Voyager isn't as tightly coupled to hooks

**Comment by marktopper** [comment]
The menu item is already here.
https://github.com/the-control-group/voyager/blob/master/publishable/database/seeds/MenuItemsTableSeeder.php#L197

**Comment by fletch3555** [comment]
I'm going to close this in favor of consolidating that code into the Hooks package

**Comment by marktopper** [comment]
I will fix something up.

**Comment by akazorg** [comment]
@fletch3555 It's a total nonsense having Hooks documentation on Core, and not having Menu + Permission. This should be approved.

**Comment by fletch3555** [comment]
@akazorg I agree it's total nonsense, but I disagree that Voyager needs to be the source of that permission.  I suggested @marktopper have the voyager-hooks package add the permission, which makes much more sense, since that's the package that integrates Hooks into Voyager

**Comment by akazorg** [comment]
We need to fix this. Right now Hooks aren't working OOTB and we are shipping Voyager with it.
This PR fix it right away... I would had merge it and fix the problem.

Let's fix this guys. ^^

**Pull request closed without merging**
