### PR TITLE
Fixed incorrect field name

### PR DESCRIPTION
**Pull request by ya-tmch**
There was an error in the field name. Instead of "field" you need to use "type". Corrected on three lines.

### CODE REVIEW

**Comment by fletch3555** [comment]
Huh..... This is the first I've heard of this being an issue.  I imagine if it was a problem, it would've been reported prior to this.  @marktopper, any thoughts?

**Comment by marktopper** [comment]
I haven't heard anyone complaining about it, but when looking at this code it all makes sense using `type` instead of `field`.

I will do some proper testing of this locally.

**Comment by ya-tmch** [comment]
Apparently, the name of the field usually coincides with its type. I made a field like "file" with the name "video", and noticed that after the update the content disappears.

**Comment by marktopper** [comment]
Makes sense @ya-tmch.

Just tested, works perfectly.
Thanks, merging in.

**Pull request merged**
