### PR TITLE
Refactoring admin_menu

### PR DESCRIPTION
**Pull request by fletch3555**
* Admin menu now uses Laravel auth instead of checking permissions directly.
* Parent menus will hide if all children are hidden.
* Cleaned up code a bit

### CODE REVIEW

**Comment by marktopper** [comment]
Thanks @fletch3555, works like a charm

**Comment by evrend** [comment]
Thank you @fletch3555, good job

**Comment by reficul** [comment]
I don't know if this commit fix also what I found now, I report to you @fletch3555.

I try to put all items of the default voyager menu in a parent category named "Voyager". After that I notice that menu doesn't work on 2+ level of nested items. In my example I can't able to expand 'tools' because inside 'voyager' item.

**Comment by fletch3555** [comment]
That's a known issue and I think there's an open issue for it.  Please try to find it and comment there, or open a new issue if you can't find one.

**Pull request merged**
