### PR TITLE
Added ability to create custom permission per table

### PR DESCRIPTION
**Pull request by ratt**
Hi, 

Were busy implementing a workflow for certain roles that required some additional (custom) permissions. EG the ability to restrict publishing. As we work in a team these permissions get added from a seed

Usage example: Permission::generateCustomFor('post', 'publish')

### CODE REVIEW

**Comment by fletch3555** [comment]
Is there a reason you can't just create these manually in your migration?  I'm not sure our models need more one-off functions added, but I'm also not 100% opposed to it.

**Comment by ratt** [comment]
Not at all, we just create seeds similar to how you do it to preload
permissions for our custom tables. So we simply followed the same example
you did but rather created a function. We have no issues if this is not
included and just thought it might be useful.

**Comment by akazorg** [comment]
This feature is handy, we should merge this.

**Comment by fletch3555** [comment]
I'm not opposed to it, but I don't think it's necessary.  It enables a one-liner for migrations, where 2 lines normally would've sufficed.

**Comment by akazorg** [comment]
It's true, we don't need this, or we would be bloating Voyager with many handy methods.

Thanks for sharing @ratt.

**Pull request closed without merging**
