### PR TITLE
Add Support for Input Type Color

### PR DESCRIPTION
**Pull request by akazorg**
Related issues: #619 and #1493.

imagem

### CODE REVIEW

**Comment by tnylea** [comment]
@akazorg Good job man!

I'll merge this in tomorrow. I see there is a conflict that arised from a previous PR, but I can resolve it. I'll send you another message when it's been merged 👍

**Comment by akazorg** [comment]
Hello @tnylea! Thanks for the fix and merge. :)

**Comment by iSWORD** [comment]
is it possible to add more input types using [hooks](https://github.com/larapack/voyager-hooks)?

**Comment by fletch3555** [comment]
@iSWORD, this was merged 4 months ago... Please open your own issue or ask in our Slack group

**Pull request merged**
