### PR TITLE
Editable fields for pivot table

### PR DESCRIPTION
**Pull request by antranapp**
If you have many-to-many relationship in your BREAD, it's currently not convenient to enter content for that relationship.

This pull request creates an "editor" for fields in pivot table that reflects a many-to-many relationship. 
Example: Product & Feature have many-to-many relationship. 
Product Model looks like this:
````
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public function user_id()
    {
        return $this->belongsTo(User::class);
    }

    public function features()
    {
        return $this->belongsToMany(Feature::class)->withTimestamps()->withPivot('value', 'value_unit', 'value_type');
    }
}
````

The pivot table `feature_product` has some extra fields `value`, `value_unit`, `value_type`.
Now you can add an additional option `editablePivotFields` when defining relationship in BREAD for `Product` model to enable the editor for fields in pivot table.
screen shot 2017-01-21 at 23 45 28

The editor will look like this:
rz1saaoigp

### CODE REVIEW

**Comment by marktopper** [comment]
Thanks!

**Comment by marktopper** [comment]
This should be documentated.

**Comment by antranapp** [comment]
@marktopper will do that to day after work.

**Comment by marktopper** [comment]
If you are to busy, just let me know and I will do it 👍

**Comment by antranapp** [comment]
sure, could you please do it? it's our year end and things are going crazy here :)

**Comment by marktopper** [comment]
Sure, will look into it.

Happy new year then, hope you enjoy! 🎉

**Comment by husseinalaa** [comment]
I have been trying the above model with the same tables (products,features,feature_product) and couldn't achieve the +Row button not even close. if you could post an example for that many to many model.

**Comment by fletch3555** [comment]
@husseinalaa, this was merged in nearly a year ago.  It's entirely possible that this functionality changed significantly since then, including the possibility of it having been removed.  Having said that, please don't comment on such old issues/PRs.  Instead, you can either open your own, or you can post any questions on our Slack group's #help channel

**Pull request merged**
