### PR TITLE
Category parent id select dropdown

### PR DESCRIPTION
**Pull request by antranapp**
screen shot 2017-01-06 at 16 14 32

Require https://github.com/the-control-group/voyager/pull/493 to be merged first

Fix https://github.com/the-control-group/voyager/issues/474 and https://github.com/the-control-group/voyager/issues/475

### CODE REVIEW

**Comment by fletch3555** [comment]
You committed `CategoryTest.php` in both #493 and here.  I recommend removing it from both since it doesn't seem directly related to either

**Comment by marktopper** [comment]
@peacemoon: Can you make this work with the latest changes of #493

**Comment by antranapp** [comment]
I'm working on it now.

**Comment by marktopper** [comment]
I think for a foreign key like this, a empty input should become `null`, since the database expect either a foreign key or `null`.

Which means the the category table had in database relations, then a empty value would become `null`.
But in the current case it would become empty and the database could complain that a category with the id of empty string does not exists.

Thoughts?

**Comment by antranapp** [comment]
@marktopper  I don't think I get your idea. Could you elaborate it a little bit?

**Comment by antranapp** [comment]
I think I get your idea now. It's a good idea to have a foreign key constraint for `parent_id`. I also add the default value for `parent_id`to `null`. Hope it's ok now.

**Comment by marktopper** [comment]
Just gonna test this out before I merge.

**Comment by marktopper** [comment]
Works like a charm! Great work 👍

**Comment by hazem1taha** [comment]
@marktopper 

Is this PR merged to the master ? as I ran composer update` but the Category Model still doesn't has the parent_id relationship method.

    <?php

    namespace TCG\Voyager\Models;

    use Illuminate\Database\Eloquent\Model;

    class Category extends Model
    {
    protected $table = 'categories';

    protected $fillable = ['slug', 'name'];

    public function posts()
    {
        return $this->hasMany(Post::class)
            ->published()
            ->orderBy('created_at', 'DESC');
    }
    }

**Comment by marktopper** [comment]
It's merged into `master`.

https://github.com/the-control-group/voyager/blob/master/src/Models/Category.php#L20

**Comment by hazem1taha** [comment]
But why I didn't get these changes after running `composer update` ? Am I missing something ? Or do these changes need to be added to a new release to be able to get it locally using the composer command ?

**Comment by marktopper** [comment]
What does you `composer.json` say? And what version does your Voyager admin panel say on the bottom right corner?

**Comment by hazem1taha** [comment]
`v0.10.9`

    {
        "name": "laravel/laravel",
        "description": "The Laravel Framework.",
        "keywords": ["framework", "laravel"],
        "license": "MIT",
        "type": "project",
        "require": {
            "php": ">=5.6.4",
            "laravel/framework": "5.3.*",
            "tcg/voyager": "0.10.*"
        },
        "require-dev": {
            "fzaninotto/faker": "~1.4",
            "mockery/mockery": "0.9.*",
            "phpunit/phpunit": "~5.0",
            "symfony/css-selector": "3.1.*",
            "symfony/dom-crawler": "3.1.*"
        },
        "autoload": {
            "classmap": [
                "database"
            ],
            "psr-4": {
                "App\\": "app/"
            }
        },
        "autoload-dev": {
            "classmap": [
                "tests/TestCase.php"
            ]
        },
        "scripts": {
            "post-root-package-install": [
                "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
            ],
            "post-create-project-cmd": [
                "php artisan key:generate"
            ],
            "post-install-cmd": [
                "Illuminate\\Foundation\\ComposerScripts::postInstall",
                "php artisan optimize"
            ],
            "post-update-cmd": [
                "Illuminate\\Foundation\\ComposerScripts::postUpdate",
                "php artisan optimize"
            ]
        },
        "config": {
            "preferred-install": "dist"
        }
    }

**Comment by marktopper** [comment]
Just checked, it's not in a release yet.
You will have to wait for the next release or update to `dev-master`.

**Pull request merged**
