### PR TITLE
Fix route parameters

### PR DESCRIPTION
**Pull request by AdrianKuriata**
I fixed dynamic route parameters, now is working fine.

Issue #1094

### CODE REVIEW

**Comment by fletch3555** [comment]
I don't really like this solution.  I'm not saying there isn't an issue with Voyager (I haven't looked into it), but this is the first time I've heard of anyone having this issue, so it's more likely to be an issue with what you're doing.

With that said, it looks like `$parameters` is an object for you, when it should be a JSON-formatted string.

I'll let someone else dig into the specifics of that issue and attempt to reproduce it.

**Comment by AdrianKuriata** [comment]
@fletch3555 How can i understand it, you don't have this issue? I tested it on clearly install Voyager and got this issue too. 

//Edit
10 minutes ago i installed clear Laravel 5.4 and Voyager, put dynamic route name and parameter, i got error as `json_decode` need string, but got object, this is how i inserted parameter:

```
{
"posts": "1",
}
```

I tried too:
```
{
"posts":1,
}
```

Pic for you [http://i.imgur.com/hxKXy7I.png](http://i.imgur.com/hxKXy7I.png)

Same error, you can try do this and check it, i don't understand you for real. I just wanted help you improve Voyager. 

Hmm, look at this, in the tinker i find the bugged menu item and selected him, look at the `parameters` field [http://i.imgur.com/Mc0HXnR.png](http://i.imgur.com/Mc0HXnR.png)

When i try into parameter field insert:
`"posts": 1` or `"posts": "1"` i got error with missing argument for the route, look at the tinker, when i display all records for the menuitem model, you can see in the `parameters` field `null` value
[http://i.imgur.com/bzRy6d7.png](http://i.imgur.com/bzRy6d7.png), but when i found this bugged item he has other value for `parameters`, look [http://i.imgur.com/3gbcVex.png](http://i.imgur.com/3gbcVex.png).

This is really strange behavior, i needed did this fix, just this working for it, i tried some clues, but just change object to string and string to array just worked so i added this like a pull request, i said, i just wanted help Voyager. I hope this message clearly show you what is wrong with that.

This is `$data` before save menu item to the database [http://i.imgur.com/pL4SFBQ.png](http://i.imgur.com/pL4SFBQ.png) and this is `$menuItem` variable after saved menuItem to the database [http://i.imgur.com/zJuKjzH.png](http://i.imgur.com/zJuKjzH.png) To this moment is ok, but into base is saved like a object, this is really horrible.

**Comment by marktopper** [comment]
I think there are more cases to this.
Maybe this could be a solution:

```
if (is_string($parameters)) {
    $parameters = json_decode($parameters, true);
} else if (!is_array($parameters)) {
    $parameters = json_decode(json_encode($parameters), true);
}
```

**Comment by AdrianKuriata** [comment]
@marktopper I can try insert your solution and test it, but in new PR, because i missclicked and deleted branch with my solution, but in the not long future i will try modify this and i will try do it better dynamically so we don't adding `$parameters` like that.

**Comment by marktopper** [comment]
👍 @adriaanzon

**Comment by fletch3555** [comment]
Closing this pending recreation of the branch.

**Comment by ux-engineer** [comment]
This commit didn't work for me. Also as I installed Voyager just a few days ago, default value for this params field is null on the UI panel which hides placeholder text for the form field. It gets displayed only after I manually delete the text "null".

https://github.com/the-control-group/voyager/pull/1101/commits/1cb9635fc6dbf15ab9260b6a31440d22eb54cd09

**Pull request closed without merging**
