### PR TITLE
Publishable views

### PR DESCRIPTION
**Pull request by jeffochoa**
Currently, there's not an easy way to make some tweaks to the admin views. Making those views publishable will make this so much easier :smile:

### CODE REVIEW

**Comment by akazorg** [comment]
Hi @jeffochoa, I think you are able to change any view.
Please check docs: https://voyager.readme.io/docs/overriding-views, and let us know if that work for you.
Thank you!

**Comment by jeffochoa** [comment]
Hi, @akazorg !
Yes, you can do that, but is kind of limited, don't you think? What would happen if you want to change any other view besides the "bread" views, like the menu, the main layout, etc...

**Comment by akazorg** [comment]
You have a point. It's limited. I thought we were able to change that already.
We should merge this.
Thank you for the PR! :)

**Comment by fletch3555** [comment]
No, it's not limited... you can change any view that way, not just the BREAD views. This functionality is part of Laravel, not specific to Voyager. (See subsection "Overriding package views" here: https://laravel.com/docs/5.5/packages#views)

**Pull request closed without merging**
