### PR TITLE
[FIX] Add Arabic Support to Slugify

### PR DESCRIPTION
**Pull request by akazorg**
ping @EngHazem

### CODE REVIEW

**Comment by hazem1taha** [comment]
Great @akazorg 
Working perfectly.

**Comment by akazorg** [comment]
This is more a fix then adding new features. Ŵhy isn't this merged? xD

**Comment by abdgad** [comment]
@akazorg this still works for English like it used to, correct?

**Comment by akazorg** [comment]
@abdgad, yes, supports english.
I've changed the expression, it was only supporting [a-z0-9].

**Comment by abdgad** [comment]
Okay thanks (Y)

**Pull request merged**
