### PR TITLE
german language file added, translations done first iteration

### PR DESCRIPTION
**Pull request by marco-solare**
let's bring the pirates to germany! :)

I created a german language file 'publishable/lang/de/voyager.php' that currently contains all the existing translation keys from the master branch.

All english ui messages have been translated - exeptions: Where the same word in german is being used. Stuff like "Check Box" or "Text Area" does not have a german correspondance so I used the english words in this case, actually just like Bruno (@akazorg) did for the portuguese version.

I used his and the english translations as a blueprint for the german translations to try to have a corresponding style.

### CODE REVIEW

**Comment by marco-solare** [comment]
Hi guys, I fixed the StyleCI stuff (three spaces at end of line) guess some of the codeclimate stuff ("Similar Code found") can be ignored, I can however fix the "Line exceeds 120 characters; " errors if you like

**Comment by marktopper** [comment]
You may ignore CodeClimate 😄

**Comment by marktopper** [comment]
Looks good, merging in. 👍
Thanks for the pull request.

**Comment by marco-solare** [comment]
nice!

**Pull request merged**
