### PR TITLE
Feature/rtl support v1

### PR DESCRIPTION
**Pull request by mbdwey**
To enable RTL set voyager.multilingual.rtl flag  to true from voyager config file

### CODE REVIEW

**Comment by mbdwey** [comment]
I think it's good start point to accept, further improvements will be applied during usage

**Comment by akazorg** [comment]
Great improvement for Multilingual support.
Thank you @mbdwey!

**Comment by fletch3555** [comment]
Moving this to the `develop` branch so it can be released with v1.1

**Comment by hamog** [comment]
Hi, How to install?

**Comment by fletch3555** [comment]
@mbdwey, your branch is out of date.  Please update it with the latest

**Comment by mbdwey** [comment]
@fletch3555 Which branch as they changed !

**Comment by fletch3555** [comment]
Look at the "base" branch listed on this PR. In this case, it's `1.x-dev` (I think... mobile app doesn't show it)

**Comment by mmehdizadeh** [comment]
I add the 'rtl' => true, in config/voyager.php but admin section still ltr.
How can I change admin layout to rtl ?

**Comment by mbdwey** [comment]
@mehdiws if you are using this PR it should work

**Review by marktopper — APPROVED** [review]

**Pull request merged**
