### PR TITLE
Add Laravel 5.4 Support

### PR DESCRIPTION
**Pull request by marktopper**
This is now working for Laravel 5.4.

I however need some people to test out this using Laravel 5.3, since we will have backwards support for some time.

### CODE REVIEW

**Comment by pjeutr** [comment]
requirement for browser-kit-testing forces stability settings to dev, is it really needed?

```
  Problem 1
    - tcg/voyager dev-laravel-54-support requires laravel/browser-kit-testing 1.0.x-dev -> satisfiable by laravel/browser-kit-testing[1.0.x-dev] but these conflict with your requirements or minimum-stability.
```

**Comment by marktopper** [comment]
@pjeutr, thanks.
When I started working on this there was no stable release of `browser-kit-testing`.
However now there is, just sent a commit using the stable version.

__EDIT__: Also moved some dependencies to dev.

**Comment by iboldurev** [comment]
Please add support 5.4

**Comment by marktopper** [comment]
@iboldurev: This pull request adds support for Laravel 5.4 to the further release of `v0.11`.
ETA release date is on this sunday.

**Comment by zietbukuel** [comment]
I'm getting the following errors when installing.

Using laravel 5.4, voyager dev-laravel-54-support, mysql backend, php 5.6.29

`php artisan voyager:install --with-dummy`
```
Publishing the Voyager assets, database, and config files
Copied Directory [/vendor/tcg/voyager/publishable/assets] To [/public/vendor/tcg/voyager/assets]
Copied Directory [/vendor/tcg/voyager/publishable/database/migrations] To [/database/migrations]
Copied Directory [/vendor/tcg/voyager/publishable/database/seeds] To [/database/seeds]
Copied Directory [/vendor/tcg/voyager/publishable/demo_content] To [/storage/app/public]
Copied Directory [/vendor/tcg/voyager/publishable/views] To [/resources/views/vendor/voyager]
Publishing complete.
Publishing complete.
Migrating the database tables into your application
Migration table created successfully.
```
                                                                                                                                   
```
  [Illuminate\Database\QueryException]                                                                                                                                      
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique  
  `(`email`))   
```                                                                                                                                                            
                                                             
```
  [Doctrine\DBAL\Driver\PDOException]                                                                              
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes  
```
                                                                                                  
```
  [PDOException]                                                                                                   
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes  
```

When visiting /admin I get this:

> Sorry, the page you are looking for could not be found.

**Comment by renamate** [comment]
@zietbukuel this is the solution for your problem
https://laravel-news.com/laravel-5-4-key-too-long-error

**Comment by PwrSrg** [comment]
$ composer require tcg/voyager
Using version ^0.10.13 for tcg/voyager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

**Your requirements could not be resolved to an installable set of packages.**

  Problem 1
    - Installation request for tcg/voyager ^0.10.13 -> satisfiable by tcg/voyager[v0.10.13].
    - Conclusion: remove laravel/framework v5.4.10
    - Conclusion: don't install laravel/framework v5.4.10
    - tcg/voyager v0.10.13 requires illuminate/support 5.3.* -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/support v5.3.0|don't install laravel/framework v5.4.10
    - don't install illuminate/support v5.3.16|don't install laravel/framework v5.4.10
    - don't install illuminate/support v5.3.23|don't install laravel/framework v5.4.10
    - don't install illuminate/support v5.3.4|don't install laravel/framework v5.4.10
    - Installation request for laravel/framework (locked at v5.4.10, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.10].

**Installation failed, reverting ./composer.json to its original content.**

**Comment by zietbukuel** [comment]
@PwrSrg add `"tcg/voyager": "dev-laravel-54-support"` to your composer.json and run `composer update`.

Example:

```
"require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "tcg/voyager": "dev-laravel-54-support"
 },
```

**Comment by PwrSrg** [comment]
Where in composer.json file do I add that?  Everywhere I try to put it kicks an error:

[Seld\JsonLint\ParsingException]
  "./composer.json" does not contain valid JSON
  Parse error on line 50:
  ...packages": true    },}
  --------------------^
  Expected: 'STRING' - It appears you have an extra trailing comma

**Comment by cyntechtic** [comment]
I added "tcg/voyager": "dev-laravel-54-support" to my composer.json file as shown below=>

"require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "tcg/voyager": "dev-laravel-54-support"
    },
and ran composer update from my cmd line and got the error below

C:\xampp\htdocs\skill_inventory_old>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package phpunit/phpunit ~4.70 exists as phpunit/phpunit[3.7.
0, 3.7.1, 3.7.10, 3.7.11, 3.7.12, 3.7.13, 3.7.14, 3.7.15, 3.7.16, 3.7.17, 3.7.18
, 3.7.19, 3.7.2, 3.7.20, 3.7.21, 3.7.22, 3.7.23, 3.7.24, 3.7.25, 3.7.26, 3.7.27,
 3.7.28, 3.7.29, 3.7.3, 3.7.30, 3.7.31, 3.7.32, 3.7.33, 3.7.34, 3.7.35, 3.7.36,
3.7.37, 3.7.38, 3.7.4, 3.7.5, 3.7.6, 3.7.7, 3.7.8, 3.7.9, 3.7.x-dev, 4.0.0, 4.0.
1, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.1
9, 4.0.2, 4.0.20, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 4.0.x-dev, 4.
1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.x-dev, 4.2.0, 4.2.1, 4.2.2, 4
.2.3, 4.2.4, 4.2.5, 4.2.6, 4.2.x-dev, 4.3.0, 4.3.1, 4.3.2, 4.3.3, 4.3.4, 4.3.5,
4.3.x-dev, 4.4.0, 4.4.1, 4.4.2, 4.4.3, 4.4.4, 4.4.5, 4.4.x-dev, 4.5.0, 4.5.1, 4.
5.x-dev, 4.6.0, 4.6.1, 4.6.10, 4.6.2, 4.6.3, 4.6.4, 4.6.5, 4.6.6, 4.6.7, 4.6.8,
4.6.9, 4.6.x-dev, 4.7.0, 4.7.1, 4.7.2, 4.7.3, 4.7.4, 4.7.5, 4.7.6, 4.7.7, 4.7.x-
dev, 4.8.0, 4.8.1, 4.8.10, 4.8.11, 4.8.12, 4.8.13, 4.8.14, 4.8.15, 4.8.16, 4.8.1
7, 4.8.18, 4.8.19, 4.8.2, 4.8.20, 4.8.21, 4.8.22, 4.8.23, 4.8.24, 4.8.25, 4.8.26
, 4.8.27, 4.8.28, 4.8.29, 4.8.3, 4.8.30, 4.8.31, 4.8.32, 4.8.33, 4.8.34, 4.8.35,
 4.8.4, 4.8.5, 4.8.6, 4.8.7, 4.8.8, 4.8.9, 4.8.x-dev, 5.0.0, 5.0.1, 5.0.10, 5.0.
2, 5.0.3, 5.0.4, 5.0.5, 5.0.6, 5.0.7, 5.0.8, 5.0.9, 5.0.x-dev, 5.1.0, 5.1.1, 5.1
.2, 5.1.3, 5.1.4, 5.1.5, 5.1.6, 5.1.7, 5.1.x-dev, 5.2.0, 5.2.1, 5.2.10, 5.2.11,
5.2.12, 5.2.2, 5.2.3, 5.2.4, 5.2.5, 5.2.6, 5.2.7, 5.2.8, 5.2.9, 5.2.x-dev, 5.3.0
, 5.3.1, 5.3.2, 5.3.3, 5.3.4, 5.3.5, 5.3.x-dev, 5.4.0, 5.4.1, 5.4.2, 5.4.3, 5.4.
4, 5.4.5, 5.4.6, 5.4.7, 5.4.8, 5.4.x-dev, 5.5.0, 5.5.1, 5.5.2, 5.5.3, 5.5.4, 5.5
.5, 5.5.6, 5.5.7, 5.5.x-dev, 5.6.0, 5.6.1, 5.6.2, 5.6.3, 5.6.4, 5.6.5, 5.6.6, 5.
6.7, 5.6.8, 5.6.x-dev, 5.7.0, 5.7.1, 5.7.10, 5.7.11, 5.7.12, 5.7.13, 5.7.2, 5.7.
3, 5.7.4, 5.7.5, 5.7.6, 5.7.7, 5.7.8, 5.7.9, 5.7.x-dev, 6.0.0, 6.0.1, 6.0.2, 6.0
.3, 6.0.4, 6.0.5, 6.0.6, 6.0.x-dev, dev-issue-2111/assertNotContains-fails-when-
array-contains-boolean, dev-issue-2145/stop-on-failure-fails-to-stop, dev-master
, 6.1.x-dev, dev-refactor/symfony-process, dev-refactoring/symfony-var-dumper] b
ut these are rejected by your constraint.

how do I get v0.11 installed?

**Comment by marktopper** [comment]
It seems like you are requiring phpunit, which fails.

**Comment by marktopper** [comment]
Please use `v0.11.0` that have been released.

**Comment by jbaclangen** [comment]
I'm getting this error when requiring tcg/voyager

`bestpricehero@rs24 [~/public_html]# composer require tcg/voyager
Using version ^0.11.1 for tcg/voyager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: league/flysystem[1.0.35, 1.0.34].
    - Can only install one of: league/flysystem[1.0.35, 1.0.34].
    - Can only install one of: league/flysystem[1.0.35, 1.0.34].
    - tcg/voyager v0.11.1 requires league/flysystem ~1.0.35 -> satisfiable by league/flysystem[1.0.35].
    - Installation request for tcg/voyager ^0.11.1 -> satisfiable by tcg/voyager[v0.11.1].
    - Installation request for league/flysystem (locked at 1.0.34) -> satisfiable by league/flysystem[1.0.34].


Installation failed, reverting ./composer.json to its original content.
`

how can I go about this?

**Comment by marktopper** [comment]
What is your `composer.json` content?

**Comment by jbaclangen** [comment]
Here's the composer.json content:

`{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "/usr/local/bin/php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "/usr/local/bin/php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "/usr/local/bin/php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "/usr/local/bin/php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
	"cache-dir": "/home/bestpricehero/public_html/cache"
    }
}`

**Comment by jbaclangen** [comment]
I now got it, just updated league/flysystem. # composer require league/flysystem


but now i'm getting this error instead:

`bestpricehero@rs24 [~/public_html]# composer require tcg/voyager
Using version ^0.11.1 for tcg/voyager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing arrilot/laravel-widgets (3.7.0)
    Downloading: 100%

  - Installing psr/http-message (1.0.1)
    Downloading: 100%

  - Installing guzzlehttp/psr7 (1.4.0)
    Downloading: 100%

  - Installing intervention/image (2.3.11)
    Downloading: 100%

  - Installing tcg/voyager (v0.11.1)
    Downloading: 100%

intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> /usr/local/bin/php artisan optimize
Generating optimized class loader

Installation failed, reverting ./composer.json to its original content.


  [Symfony\Component\Process\Exception\RuntimeException]
  The process has been signaled with signal "9".


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...
`

Not sure as to how to go forward.

**Comment by marktopper** [comment]
Run it with the `--no-scripts` option.

**Comment by jbaclangen** [comment]
It worked. Now one last problem i have is when installing:

`bestpricehero@rs24 [~/public_html]# php artisan voyager:install --with-dummy
Publishing the Voyager assets, database, and config files
Copied Directory [/vendor/tcg/voyager/publishable/assets] To [/public/vendor/tcg/voyager/assets]
Copied Directory [/vendor/tcg/voyager/publishable/database/migrations] To [/database/migrations]
Copied Directory [/vendor/tcg/voyager/publishable/database/seeds] To [/database/seeds]
Copied Directory [/vendor/tcg/voyager/publishable/demo_content] To [/storage/app/public]
Publishing complete.
Publishing complete.
Migrating the database tables into your application


  [Illuminate\Database\QueryException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists (S
  QL: create table `users` (`id` int unsigned not null auto_increment primary key, `name`
  varchar(191) not null, `email` varchar(191) not null, `password` varchar(191) not null,
  `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp
  null) default character set utf8mb4 collate utf8mb4_unicode_ci)



  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists



  [PDOException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists

I tried to migrate:reset but have nothing to rollback.

`

**Comment by abdgad** [comment]
@jbaclangen the database already has a `users` table which maybe was not setup by a migration. Be careful if you are using a production database, you may accidentally delete data.
Another reason is maybe there are 2 migrations trying to create `users` table. Verify in `/database/migrations`, make sure there are no duplicate migrations.

**Comment by jbaclangen** [comment]
@abdgad thank finally figured it out. Had to manually get into mysql to drop the table since laravel doesn't see any migrations. Thanks

**Pull request merged**
